import { randomUUID } from 'node:crypto';
import { ProjectTemplate } from '../types';

const DEFINITIONS: Array<[ProjectTemplate['category'], string, string]> = [
  ['starter', 'React Starter', 'React'], ['starter', 'Next.js Starter', 'Next.js'], ['starter', 'Vue Starter', 'Vue'], ['starter', 'Nuxt Starter', 'Nuxt'], ['starter', 'Angular Starter', 'Angular'], ['starter', 'Svelte Starter', 'Svelte'], ['starter', 'React Native Starter', 'React Native'], ['starter', 'Flutter Starter', 'Flutter'], ['starter', 'Node.js Starter', 'Node.js'], ['starter', 'Express Starter', 'Express'], ['starter', 'NestJS Starter', 'NestJS'], ['blog', 'Blog', 'Next.js'], ['ecommerce', 'E-commerce', 'React'], ['chat', 'Realtime Chat', 'React'], ['dashboard', 'Analytics Dashboard', 'Vue'], ['crm', 'CRM', 'Next.js'], ['erp', 'ERP', 'Angular'], ['education', 'School Management', 'React'], ['marketplace', 'Marketplace', 'Next.js'], ['saas', 'SaaS', 'Next.js'], ['landing', 'Landing Page', 'React'],
];

export class TemplateRegistry {
  private templates = new Map<string, ProjectTemplate>();
  constructor() { DEFINITIONS.forEach(([category, name, framework]) => { const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-'); this.templates.set(slug, { id: `tpl_${slug}`, name, framework, category, version: '1.0.0', description: `${name} project template integrated with BrisaBase.`, files: { 'brisabase.json': JSON.stringify({ projectId: 'replace-me', organizationId: 'replace-me', environment: 'development', region: 'sa-east-1' }, null, 2), 'src/brisabase.ts': `export const brisabaseUrl = process.env.BRISABASE_URL || 'http://localhost:3000';\n`, 'README.md': `# ${name}\n\nGenerated by BrisaBase CLI.\n` }, dependencies: { '@brisabase/js': '^1.0.0' }, author: 'BrisaBase', changelog: 'Initial template release.' }); }); }
  public list(): ProjectTemplate[] { return Array.from(this.templates.values()).map((template) => structuredClone(template)); }
  public get(idOrName: string): ProjectTemplate | undefined { const item = this.templates.get(idOrName) || Array.from(this.templates.values()).find((template) => template.id === idOrName || template.name.toLowerCase() === idOrName.toLowerCase()); return item && structuredClone(item); }
  public create(input: Omit<ProjectTemplate, 'id' | 'version' | 'author' | 'changelog'> & Partial<Pick<ProjectTemplate, 'id' | 'version' | 'author' | 'changelog'>>): ProjectTemplate { const id = input.id || `tpl_${randomUUID().replace(/-/g, '').slice(0, 18)}`; const template: ProjectTemplate = { ...input, id, version: input.version || '1.0.0', author: input.author || 'BrisaBase developer', changelog: input.changelog || 'Initial release.' }; this.templates.set(id, template); return structuredClone(template); }
}
