import { randomUUID } from 'node:crypto';
import { ScalingDecision, ScalingPolicy, ServiceName } from './types';

export class Autoscaler {
  private policies = new Map<ServiceName, ScalingPolicy>();
  private decisions: ScalingDecision[] = [];
  constructor() { (['api', 'realtime', 'functions', 'storage'] as ServiceName[]).forEach((service) => this.policies.set(service, { id: `scale_${service}`, service, minReplicas: 1, maxReplicas: 12, targetCpuPct: 70, targetMemoryPct: 75, targetConnections: 1_000, enabled: true })); }
  public listPolicies(): ScalingPolicy[] { return Array.from(this.policies.values()).map((policy) => structuredClone(policy)); }
  public setPolicy(service: ServiceName, updates: Partial<Omit<ScalingPolicy, 'id' | 'service'>>): ScalingPolicy { const current = this.policies.get(service) || { id: `scale_${service}`, service, minReplicas: 1, maxReplicas: 12, targetCpuPct: 70, targetMemoryPct: 75, targetConnections: 1_000, enabled: true }; const next = { ...current, ...updates }; if (next.minReplicas < 1 || next.maxReplicas < next.minReplicas) throw new Error('Invalid scaling replica range.'); this.policies.set(service, next); return structuredClone(next); }
  public evaluate(service: ServiceName, currentReplicas: number, metrics: ScalingDecision['metrics']): ScalingDecision { const policy = this.policies.get(service) || this.setPolicy(service, {}); let desired = currentReplicas; let reason = 'Metrics are within target thresholds.'; if (!policy.enabled) reason = 'Scaling policy is disabled.'; else if (metrics.cpuUsage > policy.targetCpuPct || metrics.memoryUsage > policy.targetMemoryPct || metrics.activeConnections > policy.targetConnections || metrics.queueDepth > 100) { desired = Math.min(policy.maxReplicas, currentReplicas + Math.max(1, Math.ceil(Math.max(metrics.cpuUsage / policy.targetCpuPct, metrics.memoryUsage / policy.targetMemoryPct, metrics.activeConnections / policy.targetConnections)) - 1)); reason = 'Capacity threshold exceeded.'; } else if (metrics.cpuUsage < policy.targetCpuPct * 0.35 && metrics.memoryUsage < policy.targetMemoryPct * 0.35 && metrics.activeConnections < policy.targetConnections * 0.2 && metrics.queueDepth === 0) { desired = Math.max(policy.minReplicas, currentReplicas - 1); reason = 'Sustained low utilization.'; }
    const decision: ScalingDecision = { id: `scaleevt_${randomUUID().replace(/-/g, '').slice(0, 18)}`, service, currentReplicas, desiredReplicas: desired, reason, metrics, createdAt: new Date().toISOString(), applied: false }; this.decisions.unshift(decision); this.decisions = this.decisions.slice(0, 200); return structuredClone(decision); }
  public markApplied(id: string): ScalingDecision { const decision = this.decisions.find((item) => item.id === id); if (!decision) throw new Error('Scaling decision not found.'); decision.applied = true; return structuredClone(decision); }
  public listDecisions(): ScalingDecision[] { return this.decisions.map((item) => structuredClone(item)); }
}
