import { randomUUID } from 'node:crypto';
import { DeploymentRecord, DeploymentStrategy, InfrastructureContext, ServiceName } from './types';

export interface DeploymentAdapter { readonly provider: DeploymentRecord['provider']; deploy(record: DeploymentRecord): Promise<void>; rollback(record: DeploymentRecord): Promise<void>; }
class LogicalAdapter implements DeploymentAdapter { constructor(public readonly provider: DeploymentRecord['provider']) {} async deploy(_record: DeploymentRecord): Promise<void> {} async rollback(_record: DeploymentRecord): Promise<void> {} }

export class DeploymentManager {
  private deployments: DeploymentRecord[] = [];
  private adapters = new Map<DeploymentRecord['provider'], DeploymentAdapter>();
  constructor() { (['local', 'docker', 'kubernetes', 'nomad'] as DeploymentRecord['provider'][]).forEach((provider) => this.adapters.set(provider, new LogicalAdapter(provider))); }
  public registerAdapter(adapter: DeploymentAdapter): void { this.adapters.set(adapter.provider, adapter); }
  public list(context?: Pick<InfrastructureContext, 'organizationId' | 'projectId' | 'environmentId'>): DeploymentRecord[] { return this.deployments.filter((record) => !context || (record.organizationId === context.organizationId && record.projectId === context.projectId && record.environmentId === context.environmentId)).map((record) => structuredClone(record)); }
  public async deploy(context: InfrastructureContext, input: { service: ServiceName; version: string; strategy?: DeploymentStrategy; canaryPercent?: number; provider?: DeploymentRecord['provider'] }): Promise<DeploymentRecord> { if (!input.version?.trim()) throw new Error('Deployment version is required.'); const previous = this.deployments.find((item) => item.projectId === context.projectId && item.environmentId === context.environmentId && item.service === input.service && item.status === 'completed'); const record: DeploymentRecord = { id: `dep_${randomUUID().replace(/-/g, '').slice(0, 18)}`, organizationId: context.organizationId, projectId: context.projectId, environmentId: context.environmentId, service: input.service, version: input.version.trim(), previousVersion: previous?.version, strategy: input.strategy || 'rolling', status: 'deploying', author: context.userId || 'system', startedAt: new Date().toISOString(), canaryPercent: input.strategy === 'canary' ? Math.min(100, Math.max(1, input.canaryPercent || 10)) : undefined, provider: input.provider || 'local' }; this.deployments.unshift(record); try { await this.adapters.get(record.provider)?.deploy(record); record.status = 'completed'; record.completedAt = new Date().toISOString(); record.durationMs = Date.parse(record.completedAt) - Date.parse(record.startedAt); return structuredClone(record); } catch (error) { record.status = 'failed'; record.completedAt = new Date().toISOString(); record.durationMs = Date.parse(record.completedAt) - Date.parse(record.startedAt); throw error; } }
  public async rollback(context: InfrastructureContext, id: string): Promise<DeploymentRecord> { const source = this.deployments.find((record) => record.id === id && record.organizationId === context.organizationId && record.projectId === context.projectId && record.environmentId === context.environmentId); if (!source) throw new Error('Deployment not found.'); if (!source.previousVersion) throw new Error('Deployment has no previous version to roll back to.'); const rollback = await this.deploy(context, { service: source.service, version: source.previousVersion, strategy: 'immediate', provider: source.provider }); const stored = this.deployments.find((record) => record.id === rollback.id)!; stored.rollbackOf = source.id; source.status = 'rolled_back'; await this.adapters.get(source.provider)?.rollback(source); return structuredClone(stored); }
}
