import { Router } from 'express';
import { enterpriseEngine, EnterpriseContext } from '../enterprise/enterpriseEngine';
import { controlRepository } from '../db/controlRepository';
import { postgres } from '../db/postgres';

export const enterpriseManagementRouter=Router();
export const enterprisePublicRouter=Router();
export const scimRouter=Router();

function ctx(req:any):EnterpriseContext{if(!req.organizationId||!req.user?.id||!req.user?.role)throw new Error('Organization and administrative user scope are required.');return{organizationId:req.organizationId,userId:req.user.id,role:req.user.role,ip:req.ip,userAgent:req.headers['user-agent']};}
function fail(res:any,error:any,code='ENTERPRISE_ERROR'){const m=String(error?.message||'Enterprise operation failed.');const status=/not found/i.test(m)?404:/requires owner|permission|denied/i.test(m)?403:/invalid|required|must|verified|disabled|expired|match|HTTPS|private|reserved|unsupported|future/i.test(m)?400:500;return res.status(status).json({error:{code,message:status===500&&process.env.NODE_ENV==='production'?'Enterprise operation failed.':m}});}

enterpriseManagementRouter.get('/api/enterprise/domains',async(req,res)=>{try{res.json(await enterpriseEngine.listDomains(ctx(req)));}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/domains',async(req,res)=>{try{res.status(201).json(await enterpriseEngine.createDomain(ctx(req),req.body?.domain));}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/domains/:id/verify',async(req,res)=>{try{res.json(await enterpriseEngine.verifyDomain(ctx(req),req.params.id));}catch(e){fail(res,e);}});
enterpriseManagementRouter.delete('/api/enterprise/domains/:id',async(req,res)=>{try{(await enterpriseEngine.removeDomain(ctx(req),req.params.id))?res.status(204).end():res.status(404).json({error:{code:'DOMAIN_NOT_FOUND',message:'Enterprise domain not found.'}});}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/sso',async(req,res)=>{try{res.json(await enterpriseEngine.listSso(ctx(req)));}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/sso',async(req,res)=>{try{res.status(201).json(await enterpriseEngine.saveSso(ctx(req),req.body||{}));}catch(e){fail(res,e);}});
enterpriseManagementRouter.put('/api/enterprise/sso/:id',async(req,res)=>{try{res.json(await enterpriseEngine.saveSso(ctx(req),{...req.body,id:req.params.id}));}catch(e){fail(res,e);}});
enterpriseManagementRouter.delete('/api/enterprise/sso/:id',async(req,res)=>{try{(await enterpriseEngine.removeSso(ctx(req),req.params.id))?res.status(204).end():res.status(404).json({error:{code:'SSO_NOT_FOUND',message:'SSO connection not found.'}});}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/scim/tokens',async(req,res)=>{try{res.json(await enterpriseEngine.listScimTokens(ctx(req)));}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/scim/tokens',async(req,res)=>{try{res.status(201).json(await enterpriseEngine.createScimToken(ctx(req),req.body?.name,req.body?.expiresAt));}catch(e){fail(res,e);}});
enterpriseManagementRouter.delete('/api/enterprise/scim/tokens/:id',async(req,res)=>{try{(await enterpriseEngine.revokeScimToken(ctx(req),req.params.id))?res.status(204).end():res.status(404).json({error:{code:'SCIM_TOKEN_NOT_FOUND',message:'SCIM token not found.'}});}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/ip-allowlist',async(req,res)=>{try{res.json(await enterpriseEngine.listAllowlist(ctx(req)));}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/ip-allowlist',async(req,res)=>{try{res.status(201).json(await enterpriseEngine.addAllowlist(ctx(req),req.body?.cidr,req.body?.label));}catch(e){fail(res,e);}});
enterpriseManagementRouter.delete('/api/enterprise/ip-allowlist/:id',async(req,res)=>{try{(await enterpriseEngine.removeAllowlist(ctx(req),req.params.id))?res.status(204).end():res.status(404).json({error:{code:'ALLOWLIST_NOT_FOUND',message:'IP allowlist entry not found.'}});}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/policies',async(req,res)=>{try{res.json(await enterpriseEngine.policies(ctx(req)));}catch(e){fail(res,e);}});
enterpriseManagementRouter.put('/api/enterprise/policies/:key',async(req,res)=>{try{res.json(await enterpriseEngine.setPolicy(ctx(req),req.params.key,req.body?.value));}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/roles',async(req,res)=>{try{res.json(await enterpriseEngine.listRoles(ctx(req)));}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/roles',async(req,res)=>{try{res.status(201).json(await enterpriseEngine.saveRole(ctx(req),req.body||{}));}catch(e){fail(res,e);}});
enterpriseManagementRouter.delete('/api/enterprise/roles/:id',async(req,res)=>{try{(await enterpriseEngine.removeRole(ctx(req),req.params.id))?res.status(204).end():res.status(404).json({error:{code:'ROLE_NOT_FOUND',message:'Enterprise role not found.'}});}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/siem',async(req,res)=>{try{res.json(await enterpriseEngine.listSiem(ctx(req)));}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/siem',async(req,res)=>{try{res.status(201).json(await enterpriseEngine.saveSiem(ctx(req),req.body||{}));}catch(e){fail(res,e);}});
enterpriseManagementRouter.delete('/api/enterprise/siem/:id',async(req,res)=>{try{const rows=await postgres.query<{id:string}>('DELETE FROM enterprise_siem_sinks WHERE id=$1 AND organization_id=$2 RETURNING id',[req.params.id,ctx(req).organizationId]);rows.length?res.status(204).end():res.status(404).json({error:{code:'SIEM_NOT_FOUND',message:'SIEM sink not found.'}});}catch(e){fail(res,e);}});
enterpriseManagementRouter.post('/api/enterprise/siem/:id/deliver',async(req,res)=>{try{res.json(await enterpriseEngine.deliverSiem(ctx(req),req.params.id,Number(req.body?.limit)||100));}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/audit/export',async(req,res)=>{try{const rows=await enterpriseEngine.auditExport(ctx(req),Number(req.query.limit)||1000);if(String(req.query.format||'json')==='ndjson'){res.type('application/x-ndjson').send(rows.map(x=>JSON.stringify(x)).join('\n')+'\n');return;}res.json(rows);}catch(e){fail(res,e);}});
enterpriseManagementRouter.get('/api/enterprise/compliance',async(req,res)=>{try{res.json(await enterpriseEngine.compliance(ctx(req)));}catch(e){fail(res,e);}});

enterprisePublicRouter.get('/enterprise/v1/sso/:id/start',async(req,res)=>{try{const url=await enterpriseEngine.startSso(req.params.id,typeof req.query.redirect==='string'?req.query.redirect:undefined);res.redirect(302,url);}catch(e){fail(res,e,'SSO_START_FAILED');}});
enterprisePublicRouter.all('/enterprise/v1/sso/:id/callback',async(req,res)=>{try{const data={...req.query,...req.body};const result=await enterpriseEngine.finishSso(req.params.id,data);const url=new URL(result.redirect);url.searchParams.set('sso_ticket',result.ticket);res.redirect(302,url.toString());}catch(e){fail(res,e,'SSO_CALLBACK_FAILED');}});

const SCIM='urn:ietf:params:scim:schemas:core:2.0:User';
const LIST='urn:ietf:params:scim:api:messages:2.0:ListResponse';
async function scimAuth(req:any,res:any,next:any){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const session=await enterpriseEngine.resolveScimToken(token);if(!session){res.status(401).setHeader('WWW-Authenticate','Bearer').json({schemas:['urn:ietf:params:scim:api:messages:2.0:Error'],status:'401',detail:'Invalid SCIM token.'});return;}req.scim=session;next();}
scimRouter.use('/scim/v2',scimAuth);
const scimUser=(row:any)=>({schemas:[SCIM],id:row.user_id||row.id,userName:row.email,name:{formatted:row.name},displayName:row.name,active:row.status==='active',roles:[{value:row.role,primary:true}],meta:{resourceType:'User',created:row.created_at,lastModified:row.updated_at}});
async function resolveScimRole(organizationId:string,raw:any):Promise<string>{const role=String(raw||'developer').trim().toLowerCase();if(['admin','developer','viewer','billing'].includes(role))return role;if(role==='owner')return 'developer';const custom=(await postgres.query<{key:string}>('SELECT key FROM enterprise_roles WHERE organization_id=$1 AND key=$2',[organizationId,role]))[0];return custom?.key||'developer';}
scimRouter.get('/scim/v2/Users',async(req:any,res)=>{const rows=await postgres.query<any>('SELECT m.user_id,m.role,m.created_at,m.updated_at,u.email,u.name,u.status FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 ORDER BY m.created_at',[req.scim.organizationId]);res.json({schemas:[LIST],totalResults:rows.length,startIndex:1,itemsPerPage:rows.length,Resources:rows.map(scimUser)});});
scimRouter.get('/scim/v2/Users/:id',async(req:any,res)=>{const row=(await postgres.query<any>('SELECT m.user_id,m.role,m.created_at,m.updated_at,u.email,u.name,u.status FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.user_id=$2',[req.scim.organizationId,req.params.id]))[0];row?res.json(scimUser(row)):res.status(404).json({schemas:['urn:ietf:params:scim:api:messages:2.0:Error'],status:'404',detail:'User not found.'});});
scimRouter.post('/scim/v2/Users',async(req:any,res)=>{const email=String(req.body?.userName||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){res.status(400).json({schemas:['urn:ietf:params:scim:api:messages:2.0:Error'],status:'400',detail:'A valid userName email is required.'});return;}const role=await resolveScimRole(req.scim.organizationId,req.body?.roles?.[0]?.value);const member=await controlRepository.addMember(req.scim.organizationId,{email,role:role as any}).catch(async()=>{const user=(await postgres.query<any>('SELECT id FROM users WHERE email=$1',[email]))[0];return user?(await postgres.query<any>('SELECT * FROM organization_members WHERE organization_id=$1 AND user_id=$2',[req.scim.organizationId,user.id]))[0]:null;});const row=(await postgres.query<any>('SELECT m.user_id,m.role,m.created_at,m.updated_at,u.email,u.name,u.status FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.id=$1',[member?.id]))[0];res.status(201).json(scimUser(row));});
scimRouter.patch('/scim/v2/Users/:id',async(req:any,res)=>{const ops=Array.isArray(req.body?.Operations)?req.body.Operations:[];for(const op of ops){const path=String(op.path||'').toLowerCase();if(path==='active'&&op.op?.toLowerCase()==='replace')await postgres.execute("UPDATE users SET status=$2,updated_at=now() WHERE id=$1",[req.params.id,op.value===false?'inactive':'active']);if(path==='roles'||path==='role'){const value=Array.isArray(op.value)?op.value[0]?.value:op.value;const role=await resolveScimRole(req.scim.organizationId,value);await postgres.execute('UPDATE organization_members SET role=$3,updated_at=now() WHERE organization_id=$1 AND user_id=$2',[req.scim.organizationId,req.params.id,role]);}}const row=(await postgres.query<any>('SELECT m.user_id,m.role,m.created_at,m.updated_at,u.email,u.name,u.status FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.user_id=$2',[req.scim.organizationId,req.params.id]))[0];row?res.json(scimUser(row)):res.status(404).end();});
scimRouter.delete('/scim/v2/Users/:id',async(req:any,res)=>{await postgres.execute("DELETE FROM organization_members WHERE organization_id=$1 AND user_id=$2 AND role<>'owner'",[req.scim.organizationId,req.params.id]);res.status(204).end();});
scimRouter.get('/scim/v2/Groups',async(req:any,res)=>{const custom=await postgres.query<{key:string}>('SELECT key FROM enterprise_roles WHERE organization_id=$1 ORDER BY key',[req.scim.organizationId]);const roles=['owner','admin','developer','viewer','billing',...custom.map(x=>x.key)];const groups=[];for(const role of roles){const members=await postgres.query<any>('SELECT u.id AS value,u.name AS display FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.role=$2',[req.scim.organizationId,role]);groups.push({schemas:['urn:ietf:params:scim:schemas:core:2.0:Group'],id:`role:${role}`,displayName:role,members});}res.json({schemas:[LIST],totalResults:groups.length,startIndex:1,itemsPerPage:groups.length,Resources:groups});});
scimRouter.patch('/scim/v2/Groups/:id',async(req:any,res)=>{const requested=String(req.params.id||'').replace(/^role:/,'');const role=await resolveScimRole(req.scim.organizationId,requested);if(role!==requested||role==='owner'){res.status(400).json({schemas:['urn:ietf:params:scim:api:messages:2.0:Error'],status:'400',detail:'SCIM role group is not assignable.'});return;}const ops=Array.isArray(req.body?.Operations)?req.body.Operations:[];for(const op of ops){if(String(op.op||'').toLowerCase()!=='add')continue;const members=Array.isArray(op.value?.members)?op.value.members:Array.isArray(op.value)?op.value:[];for(const member of members){if(member?.value)await postgres.execute("UPDATE organization_members SET role=$3,updated_at=now() WHERE organization_id=$1 AND user_id=$2 AND role<>'owner'",[req.scim.organizationId,String(member.value),role]);}}res.status(204).end();});
