import crypto from 'node:crypto';
import express, { NextFunction, Request, Response, Router } from 'express';
import { verifyJwt } from '../auth/jwt';
import { controlRepository } from '../db/controlRepository';
import { realAuthRepository } from '../auth/realAuthRepository';
import { realStorageEngine } from '../storage/realStorageEngine';
import { StorageOpContext } from '../storage/types';
import { redisClient } from '../redis';
import { config } from '../config';
import { securityEngine } from '../security/securityEngine';
import { resolveControlPlaneCredential, roleAllows } from '../middleware/auth';
import { webhookEngine } from '../webhooks/webhookEngine';
import { localBillingEngine } from '../billing/localBillingEngine';

export const realStorageRouter = Router();
type StorageRequest = Request & { storageContext?: StorageOpContext };

function apiKey(req: Request): string | undefined { const value = (req.headers.apikey || req.headers['x-apikey']) as string | undefined; if (value) return value; const bearer = req.headers.authorization; return bearer?.startsWith('Bearer bb_') ? bearer.slice(7).trim() : undefined; }
function failure(res: Response, status: number, code: string, message: string): void { res.status(status).json({ error: { code, message } }); }
// storage_key identifies the internal S3 object layout. It is never exposed by
// the public Storage API, signed URLs, Function results, or SDK objects.
function publicObject<T extends { storageKey?: unknown }>(object: T): Omit<T, 'storageKey'> {
  const { storageKey: _storageKey, ...safe } = object;
  return safe;
}
const MAX_STORAGE_REQUESTS_PER_MINUTE = 120;
function storageRateHash(value: string): string { return crypto.createHash('sha256').update(value).digest('hex'); }
async function storageRateLimit(key: string, res: Response): Promise<boolean> {
  const count = await redisClient.increment(key, 60);
  res.setHeader('X-RateLimit-Limit', String(MAX_STORAGE_REQUESTS_PER_MINUTE));
  res.setHeader('X-RateLimit-Remaining', String(Math.max(0, MAX_STORAGE_REQUESTS_PER_MINUTE - count)));
  if (count > MAX_STORAGE_REQUESTS_PER_MINUTE) { failure(res,429,'RATE_LIMITED','Storage request limit exceeded.'); return false; }
  return true;
}
export async function storageGateway(req: StorageRequest, res: Response, next: NextFunction): Promise<void> {
  try {
    // Layer 1: never trust tenant headers before authentication. Rotating
    // x-project-id must not create a fresh rate-limit bucket.
    const clientIp = req.ip || req.socket?.remoteAddress || 'unknown';
    if (!await storageRateLimit(`rate:storage:preauth:${storageRateHash(clientIp)}`, res)) return;
    let context: StorageOpContext | undefined;
    if (req.path.startsWith('/api/storage') && req.headers.authorization?.startsWith('Bearer ')) {
      const admin = await resolveControlPlaneCredential(
        req.headers.authorization.slice(7).trim(),
        req.headers['x-project-id'] as string | undefined,
        req.headers['x-environment-id'] as string | undefined,
      );
      const permission = req.method === 'GET' || req.method === 'HEAD' ? 'read' : 'write';
      if (!admin?.organizationId || !admin.projectId || !admin.environmentId || !roleAllows(admin.role, permission)) return failure(res,403,'STORAGE_MANAGEMENT_FORBIDDEN','Storage management scope is denied.');
      context = { organizationId: admin.organizationId, projectId: admin.projectId, environmentId: admin.environmentId, userId: admin.user.id, role: admin.role, ip: req.ip, userAgent: req.headers['user-agent'], requestId: (req.headers['x-request-id'] as string) || `stg_${crypto.randomUUID()}` };
    }
    const raw = context ? undefined : apiKey(req);
    if (!context && raw) { const key = await controlRepository.findApiKeyByRawKey(raw); if (!key || !key.environment_id) return failure(res,401,'INVALID_API_KEY','Invalid API key.'); const project = await controlRepository.getProject(key.project_id); if (!project) return failure(res,401,'INVALID_API_KEY','API key project is unavailable.'); context = { organizationId: project.organization_id,projectId:key.project_id,environmentId:key.environment_id,userId:`api_key:${key.id}`,role:key.type==='service'?'service':key.type==='secret'?'authenticated':'anonymous',apiKeyType:key.type,bypassRls:key.type==='service'&&req.headers['x-brisabase-service-bypass']==='true',ip:req.ip,userAgent:req.headers['user-agent'],requestId:(req.headers['x-request-id'] as string)||`stg_${crypto.randomUUID()}` }; }
    else if (!context && req.headers.authorization?.startsWith('Bearer ')) { const token=verifyJwt(req.headers.authorization.slice(7).trim()); const [project,environment,session,user]=await Promise.all([controlRepository.getProject(token.project_id),controlRepository.getEnvironment(token.environment_id),realAuthRepository.findSession(token.session_id),realAuthRepository.findUserById(token.sub)]); if (!project || !environment || environment.project_id!==token.project_id || !session || session.user_id!==token.sub || session.project_id!==token.project_id || session.environment_id!==token.environment_id || !user || user.project_id!==token.project_id || user.environment_id!==token.environment_id || user.status!=='active') return failure(res,401,'INVALID_JWT','Invalid or revoked JWT.'); context={organizationId:project.organization_id,projectId:token.project_id,environmentId:token.environment_id,userId:token.sub,role:token.role==='admin'||token.role==='owner'?'admin':'authenticated',ip:req.ip,userAgent:req.headers['user-agent'],requestId:(req.headers['x-request-id'] as string)||`stg_${crypto.randomUUID()}`}; }
    if (!context) return failure(res,401,'UNAUTHORIZED','Authentication is required.');
    // Layer 2: use only server-validated tenant/principal identity. Raw
    // x-project-id and x-environment-id headers are deliberately excluded.
    const principal = context.userId || `${context.role || 'anonymous'}:${clientIp}`;
    const scopedIdentity = `${context.organizationId}:${context.projectId}:${context.environmentId}:${principal}`;
    if (!await storageRateLimit(`rate:storage:scope:${storageRateHash(scopedIdentity)}`, res)) return;
    req.storageContext=context; next();
  } catch { failure(res,503,'STORAGE_UNAVAILABLE','Storage authentication dependencies are unavailable.'); }
}
function ctx(req: StorageRequest): StorageOpContext { return req.storageContext!; }
/**
 * The real Storage route must use the same deny-by-default policy engine as
 * the REST data plane.  The old in-memory storage route already did this,
 * but the PostgreSQL/MinIO route had not yet wired the check in.
 */
function allowed(context: StorageOpContext, bucket: string, operation: 'SELECT' | 'INSERT' | 'UPDATE' | 'DELETE', objectPath = '', row?: Record<string, unknown>, proposedRow?: Record<string, unknown>): boolean {
  return securityEngine.evaluate({
    organizationId: context.organizationId,
    projectId: context.projectId,
    environmentId: context.environmentId,
    userId: context.userId,
    role: context.role,
    claims: context.claims,
    bypassRls: context.bypassRls,
    ip: context.ip,
    userAgent: context.userAgent,
    requestId: context.requestId,
  }, 'storage', `${bucket.toLowerCase()}/${objectPath}`, operation, row, proposedRow, objectPath).allowed;
}
function range(header: string | undefined, total: number): { start: number; end: number } | undefined { const match = /^bytes=(\d*)-(\d*)$/.exec(header || ''); if (!match) return undefined; const start=match[1]?Number(match[1]):Math.max(0,total-Number(match[2]||0)); const end=match[2]?Math.min(Number(match[2]),total-1):total-1; return Number.isInteger(start)&&Number.isInteger(end)&&start>=0&&end>=start&&start<total ? {start,end} : undefined; }
async function stream(req: StorageRequest,res: Response,context: StorageOpContext,bucket: string,objectPath: string, enforceRls = true): Promise<void> { const found=await realStorageEngine.object(context,bucket,objectPath); if (!found) return failure(res,404,'OBJECT_NOT_FOUND','Object not found.'); if (enforceRls && !allowed(context,bucket,'SELECT',objectPath,{path:found.path,owner_id:found.createdBy})) return failure(res,403,'RLS_DENIED','Security policy denied storage read.'); const selected=range(req.headers.range,found.size); const bytes=selected?selected.end-selected.start+1:found.size; try{await localBillingEngine.assertCanConsume(context.organizationId,'bandwidth_bytes',bytes);}catch(error:any){if(error?.code==='PLAN_LIMIT_EXCEEDED')return failure(res,429,'PLAN_LIMIT_EXCEEDED',error.message);throw error;} const value=await realStorageEngine.stream(context,bucket,objectPath,selected); if (!value) return failure(res,404,'OBJECT_NOT_FOUND','Object not found.'); const requestId=context.requestId||String(req.headers['x-request-id']||`stg_${crypto.randomUUID()}`); await localBillingEngine.recordUsage(context.organizationId,'bandwidth_bytes',bytes,'storage_download',`bandwidth:${requestId}:${bucket}:${objectPath}:${selected?`${selected.start}-${selected.end}`:'full'}`,{projectId:context.projectId,environmentId:context.environmentId,bucket,path:objectPath}); res.status(selected?206:200).setHeader('Content-Type',value.object.mimeType).setHeader('Content-Length',bytes).setHeader('Accept-Ranges','bytes').setHeader('Content-Disposition',`${value.object.contentDisposition}; filename*=UTF-8''${encodeURIComponent(value.object.name)}`); if (selected) res.setHeader('Content-Range',`bytes ${selected.start}-${selected.end}/${value.object.size}`); value.stream.on('error',()=>res.destroy()); value.stream.pipe(res); }
function metadata(req: StorageRequest): Record<string, unknown> | undefined { const source=req.headers['x-storage-metadata']; if(typeof source==='string'){try{const parsed=JSON.parse(source);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:undefined;}catch{return undefined;}}return Buffer.isBuffer(req.body)?undefined:req.body?.metadata; }
async function upload(req: StorageRequest,res: Response,bucket: string,objectPath?: string): Promise<void> { const filePath=objectPath || String(req.headers['x-storage-path'] || ''); const content=Buffer.isBuffer(req.body)?req.body:Buffer.from(req.body?.base64 || '', 'base64'); if (!filePath || !content.length) return failure(res,400,'INVALID_INPUT','Object path and content are required.'); try { const current=await realStorageEngine.object(ctx(req),bucket,filePath); const operation=current?'UPDATE':'INSERT'; if (!allowed(ctx(req),bucket,operation,filePath,current?{path:current.path,owner_id:current.createdBy}:undefined,{path:filePath,owner_id:ctx(req).userId})) return failure(res,403,'RLS_DENIED','Security policy denied storage write.'); const delta=Math.max(0,content.length-Number(current?.size||0)); if(delta)await localBillingEngine.assertCanConsume(ctx(req).organizationId,'storage_bytes',delta); const object=await realStorageEngine.upload(ctx(req),bucket,filePath,content,String(req.headers['content-type']||req.body?.mimeType||'application/octet-stream').split(';')[0],{metadata:metadata(req),cacheControl:req.headers['cache-control'] as string|undefined,contentDisposition:req.headers['x-content-disposition']==='attachment'?'attachment':'inline'}); void webhookEngine.emit(ctx(req),current?'storage.object.updated':'storage.object.created',{bucket,path:object.path,size:object.size,mimeType:object.mimeType,version:object.version},ctx(req).requestId); res.status(201).json(publicObject(object)); } catch (error:any) { failure(res,error?.code==='PLAN_LIMIT_EXCEEDED'?429:400,error?.code==='PLAN_LIMIT_EXCEEDED'?'PLAN_LIMIT_EXCEEDED':'STORAGE_ERROR',error instanceof Error?error.message:'Unable to upload object.'); } }

realStorageRouter.use((req: StorageRequest, res, next) => {
  if (/^\/storage\/v1\/object\/(?:sign|upload|public)\//.test(req.path)) { next(); return; }
  if (req.path.startsWith('/api/storage') || req.path.startsWith('/storage/v1/')) { void storageGateway(req, res, next); return; }
  next();
});
realStorageRouter.get('/api/storage/health', async (_req,res)=>res.json(await realStorageEngine.health()));
realStorageRouter.get('/api/storage/buckets', async (req: StorageRequest,res)=>res.json(await realStorageEngine.listBuckets(ctx(req))));
realStorageRouter.post('/api/storage/buckets', async (req: StorageRequest,res)=>{ try { const value=await realStorageEngine.createBucket(ctx(req),req.body||{}); void webhookEngine.emit(ctx(req),'storage.bucket.created',{bucket:value.name,bucketId:value.id},ctx(req).requestId); res.status(201).json(value); } catch(error){ failure(res,400,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to create bucket.'); }});
realStorageRouter.patch('/api/storage/buckets/:bucket', async (req: StorageRequest,res)=>{ try { const value=await realStorageEngine.updateBucket(ctx(req),req.params.bucket,req.body||{}); if(!value)return failure(res,404,'BUCKET_NOT_FOUND','Bucket not found.');void webhookEngine.emit(ctx(req),'storage.bucket.updated',{bucket:value.name,bucketId:value.id},ctx(req).requestId);res.json(value); }catch(error){failure(res,400,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to update bucket.');}});
realStorageRouter.delete('/api/storage/buckets/:bucket', async(req: StorageRequest,res)=>{try{const deleted=await realStorageEngine.deleteBucket(ctx(req),req.params.bucket);if(!deleted)return failure(res,404,'BUCKET_NOT_FOUND','Bucket not found.');void webhookEngine.emit(ctx(req),'storage.bucket.deleted',{bucket:req.params.bucket},ctx(req).requestId);res.json({success:true});}catch(error){failure(res,409,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to delete bucket.');}});
realStorageRouter.get('/api/storage/buckets/:bucket/objects',async(req:StorageRequest,res)=>{try{const listed=await realStorageEngine.listObjects(ctx(req),req.params.bucket,{prefix:typeof req.query.prefix==='string'?req.query.prefix:undefined,limit:Number(req.query.limit)||100,offset:Number(req.query.offset)||0});const objects=listed.objects.filter((object)=>allowed(ctx(req),req.params.bucket,'SELECT',object.path,{path:object.path,owner_id:object.createdBy})).map(publicObject);res.json({...listed,total:objects.length,objects});}catch(error){failure(res,404,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to list objects.');}});
realStorageRouter.post('/api/storage/buckets/:bucket/upload',express.raw({type:()=>true,limit:'100mb'}),(req:StorageRequest,res)=>void upload(req,res,req.params.bucket));
realStorageRouter.get('/api/storage/buckets/:bucket/download/*',(req:StorageRequest,res)=>void stream(req,res,ctx(req),req.params.bucket,String((req.params as any)[0]||'')));
realStorageRouter.delete('/api/storage/buckets/:bucket/objects/*',async(req:StorageRequest,res)=>{try{const objectPath=String((req.params as any)[0]||'');const object=await realStorageEngine.object(ctx(req),req.params.bucket,objectPath);if(!object)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');if(!allowed(ctx(req),req.params.bucket,'DELETE',objectPath,{path:object.path,owner_id:object.createdBy}))return failure(res,403,'RLS_DENIED','Security policy denied storage delete.');const deleted=await realStorageEngine.remove(ctx(req),req.params.bucket,objectPath,req.query.soft!=='false');if(!deleted)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');void webhookEngine.emit(ctx(req),'storage.object.deleted',{bucket:req.params.bucket,path:objectPath,soft:req.query.soft!=='false'},ctx(req).requestId);res.json({success:true});}catch(error){failure(res,400,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to delete object.');}});
realStorageRouter.post('/api/storage/buckets/:bucket/restore',async(req:StorageRequest,res)=>{const objectPath=String(req.body?.path||'');if(!allowed(ctx(req),req.params.bucket,'UPDATE',objectPath,undefined,{path:objectPath,owner_id:ctx(req).userId}))return failure(res,403,'RLS_DENIED','Security policy denied storage restore.');const value=await realStorageEngine.restore(ctx(req),req.params.bucket,objectPath);if(!value)return failure(res,404,'OBJECT_NOT_FOUND','Deleted object not found.');void webhookEngine.emit(ctx(req),'storage.object.restored',{bucket:req.params.bucket,path:objectPath},ctx(req).requestId);res.json(publicObject(value));});
realStorageRouter.get('/api/storage/buckets/:bucket/versions',async(req:StorageRequest,res)=>{try{const objectPath=String(req.query.path||'');const object=await realStorageEngine.object(ctx(req),req.params.bucket,objectPath);if(!object)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');if(!allowed(ctx(req),req.params.bucket,'SELECT',objectPath,{path:object.path,owner_id:object.createdBy}))return failure(res,403,'RLS_DENIED','Security policy denied storage versions.');res.json((await realStorageEngine.versions(ctx(req),req.params.bucket,objectPath)).map(publicObject));}catch(error){failure(res,404,'OBJECT_NOT_FOUND',error instanceof Error?error.message:'Object not found.');}});
realStorageRouter.post('/api/storage/signed-upload-url',async(req:StorageRequest,res)=>{const objectPath=String(req.body?.path||'');if(!objectPath)return failure(res,400,'INVALID_INPUT','Object path is required.');if(!allowed(ctx(req),String(req.body?.bucket||''),'INSERT',objectPath,undefined,{path:objectPath,owner_id:ctx(req).userId}))return failure(res,403,'RLS_DENIED','Security policy denied signed upload URL.');const value=realStorageEngine.signedToken(ctx(req),req.body.bucket,objectPath,'upload',Number(req.body.expiresIn)||60);const pathname=`/storage/v1/object/upload/${encodeURIComponent(req.body.bucket)}/${objectPath.split('/').map(encodeURIComponent).join('/')}?token=${encodeURIComponent(value.token)}`;res.json({signedUrl:config.publicUrl(pathname,'storage'),expiresAt:value.expiresAt});});
realStorageRouter.post('/api/storage/buckets/:bucket/copy',async(req:StorageRequest,res)=>{try{const from=String(req.body?.from||''),to=String(req.body?.to||'');const source=await realStorageEngine.object(ctx(req),req.params.bucket,from);if(!source)return failure(res,404,'OBJECT_NOT_FOUND','Source object not found.');if(!allowed(ctx(req),req.params.bucket,'SELECT',from,{path:source.path,owner_id:source.createdBy})||!allowed(ctx(req),req.params.bucket,'INSERT',to,undefined,{path:to,owner_id:ctx(req).userId}))return failure(res,403,'RLS_DENIED','Security policy denied storage copy.');const value=await realStorageEngine.copyObject(ctx(req),req.params.bucket,from,to);void webhookEngine.emit(ctx(req),'storage.object.copied',{bucket:req.params.bucket,from,to},ctx(req).requestId);res.status(201).json(publicObject(value));}catch(error){failure(res,400,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to copy object.');}});
realStorageRouter.post('/api/storage/buckets/:bucket/move',async(req:StorageRequest,res)=>{try{const from=String(req.body?.from||''),to=String(req.body?.to||'');const source=await realStorageEngine.object(ctx(req),req.params.bucket,from);if(!source)return failure(res,404,'OBJECT_NOT_FOUND','Source object not found.');if(!allowed(ctx(req),req.params.bucket,'DELETE',from,{path:source.path,owner_id:source.createdBy})||!allowed(ctx(req),req.params.bucket,'INSERT',to,undefined,{path:to,owner_id:ctx(req).userId}))return failure(res,403,'RLS_DENIED','Security policy denied storage move.');const value=await realStorageEngine.moveObject(ctx(req),req.params.bucket,from,to);void webhookEngine.emit(ctx(req),'storage.object.moved',{bucket:req.params.bucket,from,to},ctx(req).requestId);res.json(publicObject(value));}catch(error){failure(res,400,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to move object.');}});
realStorageRouter.post('/api/storage/buckets/:bucket/multipart',async(req:StorageRequest,res)=>{try{const objectPath=String(req.body?.path||'');if(!allowed(ctx(req),req.params.bucket,'INSERT',objectPath,undefined,{path:objectPath,owner_id:ctx(req).userId}))return failure(res,403,'RLS_DENIED','Security policy denied multipart upload.');res.status(201).json(await realStorageEngine.initiateMultipart(ctx(req),req.params.bucket,objectPath,String(req.body?.mimeType||'application/octet-stream'),{metadata:req.body?.metadata,cacheControl:req.body?.cacheControl,contentDisposition:req.body?.contentDisposition},Number(req.body?.expiresIn)||86400));}catch(error){failure(res,400,'MULTIPART_ERROR',error instanceof Error?error.message:'Unable to initiate multipart upload.');}});
realStorageRouter.get('/api/storage/multipart/:uploadId',async(req:StorageRequest,res)=>{const value=await realStorageEngine.multipartStatus(ctx(req),req.params.uploadId);if(!value)return failure(res,404,'MULTIPART_NOT_FOUND','Multipart upload not found.');res.json(value);});
realStorageRouter.put('/api/storage/multipart/:uploadId/parts/:partNumber',express.raw({type:()=>true,limit:'32mb'}),async(req:StorageRequest,res)=>{try{if(!Buffer.isBuffer(req.body))return failure(res,400,'INVALID_INPUT','Raw multipart part bytes are required.');res.status(201).json(await realStorageEngine.uploadMultipartPart(ctx(req),req.params.uploadId,Number(req.params.partNumber),req.body));}catch(error){failure(res,400,'MULTIPART_ERROR',error instanceof Error?error.message:'Unable to upload multipart part.');}});
realStorageRouter.post('/api/storage/multipart/:uploadId/complete',async(req:StorageRequest,res)=>{try{const status=await realStorageEngine.multipartStatus(ctx(req),req.params.uploadId);if(!status)return failure(res,404,'MULTIPART_NOT_FOUND','Multipart upload not found.');await localBillingEngine.assertCanConsume(ctx(req).organizationId,'storage_bytes',Number(status.uploadedBytes||0));const object=await realStorageEngine.completeMultipart(ctx(req),req.params.uploadId);void webhookEngine.emit(ctx(req),'storage.multipart.completed',{uploadId:req.params.uploadId,bucketId:object.bucketId,path:object.path,size:object.size},ctx(req).requestId);res.json(publicObject(object));}catch(error){failure(res,400,'MULTIPART_ERROR',error instanceof Error?error.message:'Unable to complete multipart upload.');}});
realStorageRouter.delete('/api/storage/multipart/:uploadId',async(req:StorageRequest,res)=>{try{if(!await realStorageEngine.abortMultipart(ctx(req),req.params.uploadId))return failure(res,404,'MULTIPART_NOT_FOUND','Multipart upload not found.');res.json({success:true});}catch(error){failure(res,400,'MULTIPART_ERROR',error instanceof Error?error.message:'Unable to abort multipart upload.');}});
realStorageRouter.post('/api/storage/buckets/:bucket/lifecycle/run',async(req:StorageRequest,res)=>{try{const result=await realStorageEngine.applyLifecycle(ctx(req),req.params.bucket);void webhookEngine.emit(ctx(req),'storage.lifecycle.completed',{bucket:req.params.bucket,...result},ctx(req).requestId);res.json(result);}catch(error){failure(res,400,'LIFECYCLE_ERROR',error instanceof Error?error.message:'Unable to apply lifecycle rules.');}});
realStorageRouter.get('/api/storage/buckets/:bucket/transform/*',async(req:StorageRequest,res)=>{try{const objectPath=String((req.params as any)[0]||'');const source=await realStorageEngine.object(ctx(req),req.params.bucket,objectPath);if(!source)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');if(!allowed(ctx(req),req.params.bucket,'SELECT',objectPath,{path:source.path,owner_id:source.createdBy}))return failure(res,403,'RLS_DENIED','Security policy denied image transformation.');const transformed=await realStorageEngine.transformImage(ctx(req),req.params.bucket,objectPath,{width:Number(req.query.width)||undefined,height:Number(req.query.height)||undefined,resize:req.query.resize as any,crop:req.query.crop as any,rotate:Number(req.query.rotate)||undefined,quality:Number(req.query.quality)||undefined,format:req.query.format as any});res.setHeader('Content-Type',transformed.mimeType);res.setHeader('Content-Length',String(transformed.buffer.length));res.setHeader('ETag',transformed.etag);res.setHeader('Cache-Control','private, max-age=3600');res.send(transformed.buffer);}catch(error){failure(res,400,'TRANSFORM_ERROR',error instanceof Error?error.message:'Unable to transform image.');}});
realStorageRouter.post('/api/storage/signed-url',async(req:StorageRequest,res)=>{const object=await realStorageEngine.object(ctx(req),req.body?.bucket,req.body?.path);if(!object)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');if(!allowed(ctx(req),req.body.bucket,'SELECT',String(req.body.path),{path:object.path,owner_id:object.createdBy}))return failure(res,403,'RLS_DENIED','Security policy denied signed URL.');const value=realStorageEngine.signedToken(ctx(req),req.body.bucket,req.body.path,'read',Number(req.body.expiresIn)||60);const pathname=`/storage/v1/object/sign/${encodeURIComponent(req.body.bucket)}/${String(req.body.path).split('/').map(encodeURIComponent).join('/')}?token=${encodeURIComponent(value.token)}`;res.json({signedUrl:config.publicUrl(pathname,'storage'),expiresAt:value.expiresAt});});
realStorageRouter.get('/api/storage/usage',async(req:StorageRequest,res)=>res.json(await realStorageEngine.usage(ctx(req))));

realStorageRouter.get('/storage/v1/object/list/:bucket',async(req:StorageRequest,res)=>{try{const listed=await realStorageEngine.listObjects(ctx(req),req.params.bucket,{prefix:typeof req.query.prefix==='string'?req.query.prefix:undefined,limit:Number(req.query.limit)||100,offset:Number(req.query.offset)||0});const objects=listed.objects.filter((object)=>allowed(ctx(req),req.params.bucket,'SELECT',object.path,{path:object.path,owner_id:object.createdBy})).map(publicObject);res.json({...listed,total:objects.length,objects});}catch(error){failure(res,404,'STORAGE_ERROR',error instanceof Error?error.message:'Unable to list objects.');}});
realStorageRouter.post('/storage/v1/object/signed/:bucket',async(req:StorageRequest,res)=>{const object=await realStorageEngine.object(ctx(req),req.params.bucket,req.body?.path);if(!object)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');if(!allowed(ctx(req),req.params.bucket,'SELECT',String(req.body.path),{path:object.path,owner_id:object.createdBy}))return failure(res,403,'RLS_DENIED','Security policy denied signed URL.');const value=realStorageEngine.signedToken(ctx(req),req.params.bucket,req.body.path,'read',Number(req.body.expiresIn)||60);const pathname=`/storage/v1/object/sign/${encodeURIComponent(req.params.bucket)}/${String(req.body.path).split('/').map(encodeURIComponent).join('/')}?token=${encodeURIComponent(value.token)}`;res.json({signedUrl:config.publicUrl(pathname,'storage'),expiresAt:value.expiresAt});});
// These routes must precede the generic /object/:bucket/* handlers: otherwise
// "sign" and "upload" are parsed as a bucket name and signed URLs lose their
// verified scope.
realStorageRouter.get('/storage/v1/object/sign/:bucket/*',async(req:StorageRequest,res)=>{const decoded=realStorageEngine.resolveToken(String(req.query.token||''),'read');if(!decoded||decoded.bucket!==req.params.bucket||decoded.path!==String((req.params as any)[0]||''))return failure(res,403,'INVALID_SIGNED_URL','Invalid or expired signed URL.');await stream(req,res,decoded.ctx,decoded.bucket,decoded.path,false);});
realStorageRouter.put('/storage/v1/object/upload/:bucket/*',express.raw({type:()=>true,limit:'100mb'}),async(req:StorageRequest,res)=>{const decoded=realStorageEngine.resolveToken(String(req.query.token||''),'upload');if(!decoded||decoded.bucket!==req.params.bucket||decoded.path!==String((req.params as any)[0]||''))return failure(res,403,'INVALID_SIGNED_URL','Invalid or expired signed URL.');req.storageContext=decoded.ctx;await upload(req,res,decoded.bucket,decoded.path);});
// SDK-compatible object routes. They must come before the generic object
// handlers below so `restore` and `versions` are not parsed as bucket names.
realStorageRouter.get('/storage/v1/object/versions/:bucket',async(req:StorageRequest,res)=>{try{const objectPath=String(req.query.path||'');const object=await realStorageEngine.object(ctx(req),req.params.bucket,objectPath);if(!object)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');if(!allowed(ctx(req),req.params.bucket,'SELECT',objectPath,{path:object.path,owner_id:object.createdBy}))return failure(res,403,'RLS_DENIED','Security policy denied storage versions.');res.json((await realStorageEngine.versions(ctx(req),req.params.bucket,objectPath)).map(publicObject));}catch(error){failure(res,404,'OBJECT_NOT_FOUND',error instanceof Error?error.message:'Object not found.');}});
realStorageRouter.post('/storage/v1/object/restore/:bucket',async(req:StorageRequest,res)=>{const objectPath=String(req.body?.path||'');if(!allowed(ctx(req),req.params.bucket,'UPDATE',objectPath,undefined,{path:objectPath,owner_id:ctx(req).userId}))return failure(res,403,'RLS_DENIED','Security policy denied storage restore.');const value=await realStorageEngine.restore(ctx(req),req.params.bucket,objectPath);if(!value)return failure(res,404,'OBJECT_NOT_FOUND','Deleted object not found.');void webhookEngine.emit(ctx(req),'storage.object.restored',{bucket:req.params.bucket,path:objectPath},ctx(req).requestId);res.json(publicObject(value));});
realStorageRouter.get('/storage/v1/object/:bucket/*',(req:StorageRequest,res)=>void stream(req,res,ctx(req),req.params.bucket,String((req.params as any)[0]||'')));
realStorageRouter.post('/storage/v1/object/:bucket/*',express.raw({type:()=>true,limit:'100mb'}),(req:StorageRequest,res)=>void upload(req,res,req.params.bucket,String((req.params as any)[0]||'')));
realStorageRouter.delete('/storage/v1/object/:bucket/*',async(req:StorageRequest,res)=>{const objectPath=String((req.params as any)[0]||'');const object=await realStorageEngine.object(ctx(req),req.params.bucket,objectPath);if(!object)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');if(!allowed(ctx(req),req.params.bucket,'DELETE',objectPath,{path:object.path,owner_id:object.createdBy}))return failure(res,403,'RLS_DENIED','Security policy denied storage delete.');const deleted=await realStorageEngine.remove(ctx(req),req.params.bucket,objectPath,req.query.soft!=='false');if(!deleted)return failure(res,404,'OBJECT_NOT_FOUND','Object not found.');void webhookEngine.emit(ctx(req),'storage.object.deleted',{bucket:req.params.bucket,path:objectPath,soft:req.query.soft!=='false'},ctx(req).requestId);res.json({success:true});});
realStorageRouter.options('/storage/v1/object/public/:bucket/*',async(req:StorageRequest,res)=>{try{const projectId=String(req.query.project||'');const environmentId=String(req.query.environment||'');const project=await controlRepository.getProject(projectId);if(!project)return failure(res,404,'NOT_FOUND','Bucket not found.');const publicContext:StorageOpContext={organizationId:project.organization_id,projectId,environmentId,role:'anonymous'};const bucket=(await realStorageEngine.listBuckets(publicContext)).find((item)=>item.name===req.params.bucket&&item.isPublic);if(!bucket)return failure(res,404,'NOT_FOUND','Bucket not found.');const origin=String(req.headers.origin||'');const headers=realStorageEngine.corsHeaders(bucket,origin,String(req.headers['access-control-request-method']||'GET'));if(!Object.keys(headers).length)return failure(res,403,'CORS_DENIED','Bucket CORS policy denied this origin.');for(const [key,value] of Object.entries(headers))res.setHeader(key,value);res.status(204).end();}catch(error){failure(res,400,'CORS_ERROR',error instanceof Error?error.message:'Unable to evaluate CORS.');}});
realStorageRouter.get('/storage/v1/object/public/:bucket/*',async(req:StorageRequest,res)=>{const projectId=String(req.query.project||'');const environmentId=String(req.query.environment||'');const project=await controlRepository.getProject(projectId);if(!project)return failure(res,404,'NOT_FOUND','Object not found.');const publicContext:StorageOpContext={organizationId:project.organization_id,projectId,environmentId,role:'anonymous'};const bucket=(await realStorageEngine.listBuckets(publicContext)).find((item)=>item.name===req.params.bucket&&item.isPublic);if(!bucket)return failure(res,404,'NOT_FOUND','Object not found.');const origin=String(req.headers.origin||'');if(origin){const headers=realStorageEngine.corsHeaders(bucket,origin,'GET');for(const [key,value] of Object.entries(headers))res.setHeader(key,value);}await stream(req,res,publicContext,req.params.bucket,String((req.params as any)[0]||''),false);});
