import React, { FormEvent, useEffect, useState } from 'react';
import { Globe2, Plus, UploadCloud, ExternalLink, RotateCcw, Power, RefreshCw, ShieldCheck, Copy, Trash2, Settings2 } from 'lucide-react';
import { hostingService, HostingDeployment, HostingSite, HostingDomain } from '../services/platformCompletionService';

function toBase64(file: File): Promise<string> { return new Promise((resolve,reject)=>{ const reader=new FileReader(); reader.onerror=()=>reject(reader.error||new Error('Falha ao ler arquivo.')); reader.onload=()=>{const value=String(reader.result||'');resolve(value.includes(',')?value.slice(value.indexOf(',')+1):value);}; reader.readAsDataURL(file); }); }

export const HostingPage: React.FC = () => {
  const [sites,setSites]=useState<HostingSite[]>([]); const [selected,setSelected]=useState<HostingSite|null>(null); const [deployments,setDeployments]=useState<HostingDeployment[]>([]); const [domains,setDomains]=useState<HostingDomain[]>([]);
  const [name,setName]=useState('Meu site'); const [slug,setSlug]=useState('meu-site'); const [domain,setDomain]=useState(''); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [dnsHint,setDnsHint]=useState<string>('');
  const [redirectsText,setRedirectsText]=useState('[]'); const [rewritesText,setRewritesText]=useState('[]'); const [publicEnvText,setPublicEnvText]=useState('{}');
  const syncConfig=(site:HostingSite|null)=>{const config=site?.config||{redirects:[],rewrites:[],publicEnv:{}};setRedirectsText(JSON.stringify(config.redirects||[],null,2));setRewritesText(JSON.stringify(config.rewrites||[],null,2));setPublicEnvText(JSON.stringify(config.publicEnv||{},null,2));};
  const loadSelected=async(site:HostingSite|null)=>{syncConfig(site);setDeployments(site?await hostingService.listDeployments(site.id):[]);setDomains(site?await hostingService.listDomains(site.id):[]);};
  const load=async()=>{setError(null);try{const list=await hostingService.listSites();setSites(list);const current=selected?list.find(item=>item.id===selected.id)||null:list[0]||null;setSelected(current);await loadSelected(current);}catch(cause:any){setError(cause?.message||'Não foi possível carregar o Hosting.');}};
  useEffect(()=>{void load();},[]);
  const select=async(site:HostingSite)=>{setSelected(site);setError(null);try{await loadSelected(site);}catch(cause:any){setError(cause?.message||'Falha ao carregar site.');}};
  const createSite=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError(null);try{const site=await hostingService.createSite({name:name.trim(),slug:slug.trim()||undefined});setSites(current=>[site,...current]);await select(site);}catch(cause:any){setError(cause?.message||'Falha ao criar site.');}finally{setBusy(false);}};
  const deploy=async()=>{if(!selected||!files.length)return;setBusy(true);setError(null);try{const total=files.reduce((sum,file)=>sum+file.size,0);if(total>700_000)throw new Error('O deploy pelo navegador é limitado a ~700 KB por requisição. Para builds maiores use: brisabase hosting deploy <siteId> <dist>.');const payload=await Promise.all(files.map(async file=>({path:(file as any).webkitRelativePath||file.name,contentBase64:await toBase64(file),mimeType:file.type||undefined})));if(!payload.some(item=>item.path.endsWith('index.html')))throw new Error('Selecione um build que contenha index.html.');await hostingService.deployFiles(selected.id,payload);setFiles([]);await load();}catch(cause:any){setError(cause?.message||'Falha no deploy.');}finally{setBusy(false);}};
  const activate=async(item:HostingDeployment)=>{if(!selected)return;setBusy(true);try{await hostingService.activate(selected.id,item.id);await load();}catch(cause:any){setError(cause?.message||'Falha ao ativar deploy.');}finally{setBusy(false);}};
  const disable=async()=>{if(!selected||!confirm(`Desabilitar o site “${selected.name}”?`))return;setBusy(true);try{await hostingService.disableSite(selected.id);setSelected(null);await load();}catch(cause:any){setError(cause?.message||'Falha ao desabilitar site.');}finally{setBusy(false);}};
  const addDomain=async()=>{if(!selected||!domain.trim())return;setBusy(true);setError(null);try{const created=await hostingService.addDomain(selected.id,domain.trim());setDnsHint(created.dnsRecord?`${created.dnsRecord.type} ${created.dnsRecord.name} = ${created.dnsRecord.value}`:'');setDomain('');setDomains(await hostingService.listDomains(selected.id));}catch(cause:any){setError(cause?.message||'Falha ao adicionar domínio.');}finally{setBusy(false);}};
  const verify=async(item:HostingDomain)=>{if(!selected)return;setBusy(true);try{await hostingService.verifyDomain(selected.id,item.id);setDomains(await hostingService.listDomains(selected.id));}catch(cause:any){setError(cause?.message||'TXT ainda não encontrado.');}finally{setBusy(false);}};
  const removeDomain=async(item:HostingDomain)=>{if(!selected||!confirm(`Remover ${item.hostname}?`))return;await hostingService.removeDomain(selected.id,item.id);setDomains(await hostingService.listDomains(selected.id));};
  const saveConfig=async()=>{if(!selected)return;setBusy(true);setError(null);try{const redirects=JSON.parse(redirectsText);const rewrites=JSON.parse(rewritesText);const publicEnv=JSON.parse(publicEnvText);if(!Array.isArray(redirects)||!Array.isArray(rewrites)||!publicEnv||Array.isArray(publicEnv)||typeof publicEnv!=='object')throw new Error('Redirects/rewrites devem ser arrays JSON e Public Env deve ser um objeto JSON.');const updated=await hostingService.updateConfig(selected.id,{redirects,rewrites,publicEnv});setSelected(updated);setSites(current=>current.map(item=>item.id===updated.id?updated:item));syncConfig(updated);}catch(cause:any){setError(cause?.message||'Falha ao salvar configuração do Hosting.');}finally{setBusy(false);}};

  return <div className="space-y-6 pb-12">
    <div className="flex flex-col gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold text-slate-100"><Globe2 className="h-5 w-5 text-purple-400"/>Static Hosting</h1><p className="mt-1 text-xs text-slate-400">Deploys versionados no Storage, previews imutáveis, rollback e domínios customizados com DNS + TLS automático via Caddy.</p></div><button onClick={()=>void load()} disabled={busy} className="flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-800 px-4 py-2.5 text-xs font-semibold text-slate-200 hover:bg-slate-700"><RefreshCw className="h-4 w-4"/>Atualizar</button></div>
    {error&&<div className="rounded-xl border border-red-800 bg-red-950/50 p-4 text-sm text-red-300">{error}</div>}
    <form onSubmit={createSite} className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="space-y-1.5 text-xs text-slate-400">Nome<input value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-slate-100"/></label><label className="space-y-1.5 text-xs text-slate-400">Slug<input value={slug} onChange={e=>setSlug(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-slate-100"/></label><button disabled={busy||!name.trim()} className="flex items-center gap-2 rounded-xl bg-purple-600 px-4 py-2.5 text-xs font-semibold text-white"><Plus className="h-4 w-4"/>Novo site</button></form>
    <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><div className="h-fit rounded-2xl border border-slate-800 bg-slate-900/60 p-3"><div className="px-2 pb-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">Sites ({sites.length})</div>{sites.length===0?<div className="px-2 py-6 text-center text-xs text-slate-500">Nenhum site.</div>:sites.map(site=><button key={site.id} onClick={()=>void select(site)} className={`mb-1 w-full rounded-xl border px-3 py-3 text-left ${selected?.id===site.id?'border-purple-500/40 bg-purple-600/15':'border-transparent hover:bg-slate-800'}`}><div className="font-semibold text-slate-200">{site.name}</div><div className="mt-1 truncate font-mono text-[10px] text-slate-500">/{site.slug}</div><div className="mt-2 text-[10px] uppercase text-emerald-400">{site.status}</div></button>)}</div>
      <div className="space-y-4">{selected?<><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-slate-100">{selected.name}</h2><a href={selected.builtInUrl} target="_blank" rel="noreferrer" className="mt-1 flex items-center gap-1 font-mono text-xs text-cyan-400">{selected.builtInUrl}<ExternalLink className="h-3 w-3"/></a></div><button onClick={()=>void disable()} disabled={busy} className="flex items-center gap-2 rounded-xl border border-red-900/70 px-3 py-2 text-xs text-red-300"><Power className="h-4 w-4"/>Desabilitar</button></div></div>
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="font-semibold text-slate-100">Novo deploy</h3><p className="mt-1 text-xs text-slate-500">Para builds grandes use o CLI, que envia arquivo a arquivo sem aumentar o limite JSON global.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center"><input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))} className="min-w-0 flex-1 text-xs text-slate-400"/><button onClick={()=>void deploy()} disabled={busy||!files.length} className="flex items-center justify-center gap-2 rounded-xl bg-purple-600 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40"><UploadCloud className="h-4 w-4"/>Publicar {files.length?`(${files.length})`:''}</button></div></div>
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex items-center gap-2"><Settings2 className="h-4 w-4 text-cyan-400"/><h3 className="font-semibold text-slate-100">Configuração do site</h3></div><p className="mt-1 text-xs text-slate-500">Redirects e rewrites são aplicados no runtime. Variáveis são públicas e só aceitam prefixos <code>PUBLIC_</code> ou <code>VITE_</code>; nunca coloque segredos aqui.</p><div className="mt-4 grid gap-3 xl:grid-cols-3"><label className="space-y-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500">Redirects JSON<textarea value={redirectsText} onChange={e=>setRedirectsText(e.target.value)} rows={7} spellCheck={false} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-[11px] normal-case text-slate-200"/></label><label className="space-y-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500">Rewrites JSON<textarea value={rewritesText} onChange={e=>setRewritesText(e.target.value)} rows={7} spellCheck={false} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-[11px] normal-case text-slate-200"/></label><label className="space-y-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500">Public Env JSON<textarea value={publicEnvText} onChange={e=>setPublicEnvText(e.target.value)} rows={7} spellCheck={false} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-[11px] normal-case text-slate-200"/></label></div><div className="mt-3 flex justify-end"><button onClick={()=>void saveConfig()} disabled={busy} className="rounded-xl bg-cyan-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Salvar configuração</button></div></div>
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-400"/><h3 className="font-semibold text-slate-100">Domínios customizados</h3></div><div className="mt-3 flex gap-2"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="app.exemplo.com" className="flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100"/><button onClick={()=>void addDomain()} disabled={busy||!domain.trim()} className="rounded-xl bg-slate-800 px-3 py-2 text-xs font-semibold text-white">Adicionar</button></div>{dnsHint&&<div className="mt-3 flex items-center justify-between gap-2 rounded-lg border border-cyan-900/50 bg-cyan-950/20 p-3 font-mono text-[10px] text-cyan-300"><span className="break-all">{dnsHint}</span><button onClick={()=>void navigator.clipboard.writeText(dnsHint)}><Copy className="h-3.5 w-3.5"/></button></div>}<div className="mt-3 space-y-2">{domains.map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-800 bg-slate-950/60 p-3"><div><div className="text-sm font-medium text-slate-100">{item.hostname}</div><div className="text-[10px] text-slate-500">DNS {item.status} · TLS {item.tls_status}</div></div><div className="flex gap-2">{item.status!=='verified'&&<button onClick={()=>void verify(item)} className="rounded border border-emerald-800 px-2 py-1 text-xs text-emerald-300">Verificar DNS</button>}<button onClick={()=>void removeDomain(item)} className="rounded border border-red-900 px-2 py-1 text-red-300"><Trash2 className="h-3.5 w-3.5"/></button></div></div>)}</div></div>
        <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/50"><div className="border-b border-slate-800 px-4 py-3 text-xs font-semibold text-slate-300">Deploys e previews</div>{deployments.length===0?<div className="p-8 text-center text-xs text-slate-500">Nenhum deploy.</div>:<div className="divide-y divide-slate-800">{deployments.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3"><div><div className="font-mono text-xs text-slate-200">v{item.version} · {item.status}</div><div className="mt-1 text-[10px] text-slate-500">{item.fileCount} arquivos · {(item.sizeBytes/1024).toFixed(1)} KB</div><a target="_blank" rel="noreferrer" className="mt-1 block text-[10px] text-cyan-400" href={`${selected.builtInUrl}_deploy/${item.id}/`}>preview imutável</a></div><button onClick={()=>void activate(item)} disabled={busy||item.status==='active'} className="flex items-center gap-1.5 rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-300 disabled:opacity-30"><RotateCcw className="h-3.5 w-3.5"/>{item.status==='active'?'Ativo':'Ativar / rollback'}</button></div>)}</div>}</div>
      </>:<div className="rounded-2xl border border-dashed border-slate-800 p-12 text-center text-sm text-slate-500">Crie ou selecione um site.</div>}</div></div>
  </div>;
};
