import React, { useEffect, useState } from 'react';
import { Activity, Boxes, CloudCog, Globe2, RefreshCw, ServerCog, ShieldCheck, TriangleAlert } from 'lucide-react';
import { MetricCard } from '../components/common/MetricCard';
import { StatusBadge } from '../components/common/StatusBadge';
import { infrastructureService } from '../services';

type Tab = 'Overview' | 'Instances' | 'Services' | 'Deployments' | 'Replication' | 'Networking' | 'Incidents';
const tabs: Tab[] = ['Overview','Instances','Services','Deployments','Replication','Networking','Incidents'];

async function json<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error?.message||`Request failed (${r.status}).`);return p as T;}

export const InfrastructurePage: React.FC = () => {
  const [tab,setTab]=useState<Tab>('Overview'); const [data,setData]=useState<any>({}); const [error,setError]=useState('');
  const refresh=async()=>{try{const [overview,nodes,deployments,replication,services,health,networking,incidents]=await Promise.all([infrastructureService.overview(),infrastructureService.nodes(),infrastructureService.deployments(),infrastructureService.replication(),infrastructureService.services(),infrastructureService.health(),infrastructureService.networking(),json<any[]>('/api/infrastructure/incidents')]);setData({overview,nodes,deployments,replication,services,health,networking,incidents});setError('');}catch(err:any){setError(err.message||'Unable to load production runtime.');}};
  useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(),15_000);return()=>window.clearInterval(t);},[]);
  const cluster=data.overview?.cluster||{healthy:0,degraded:0,offline:0,replicasObserved:0};
  return <div className="space-y-6 pb-12">
    <div className="flex flex-col justify-between gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:flex-row sm:items-center"><div><h1 className="flex items-center gap-2 text-xl font-bold text-slate-100"><CloudCog className="h-5 w-5 text-purple-400"/>Production Runtime</h1><p className="mt-1 text-xs text-slate-400">Estado real do runtime, dependências, réplicas observadas e incidentes. O BrisaBase não simula Multi-AZ: HA de PostgreSQL/Redis/Object Storage é responsabilidade do provedor/orquestrador configurado.</p></div><button onClick={()=>void refresh()} className="flex items-center justify-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200 hover:bg-slate-800"><RefreshCw className="h-4 w-4"/>Atualizar</button></div>
    <div className="flex gap-2 overflow-x-auto border-b border-slate-800 pb-2">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`whitespace-nowrap rounded-md px-3 py-2 text-sm ${tab===item?'bg-purple-600 text-white':'text-slate-400 hover:bg-slate-800 hover:text-white'}`}>{item}</button>)}</div>
    {error&&<div className="rounded-lg border border-red-800 bg-red-950/50 p-3 text-sm text-red-300">{error}</div>}
    {tab==='Overview'&&<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard title="Runtime" value={data.health?.status||'unknown'} badge={data.overview?.deploymentMode||'runtime'} badgeType={data.health?.status==='healthy'?'positive':'negative'} icon={ShieldCheck}/><MetricCard title="Réplicas observadas" value={cluster.replicasObserved||0} badge={`${cluster.degraded||0} degradadas`} badgeType="neutral" icon={ServerCog}/><MetricCard title="Região configurada" value={data.networking?.region||'local-1'} badge={data.overview?.productionTier||'single-host'} badgeType="neutral" icon={Globe2}/><MetricCard title="Incidentes abertos" value={(data.incidents||[]).filter((x:any)=>x.status!=='resolved').length} badge="live" badgeType="neutral" icon={TriangleAlert}/></div><Panel title="Capacidades reais"><pre className="overflow-x-auto rounded-md bg-slate-950 p-4 text-xs text-slate-300">{JSON.stringify(data.overview?.capabilities||{},null,2)}</pre></Panel></>}
    {tab==='Instances'&&<Panel title="Instâncias do BrisaBase"><List items={(data.nodes||[]).map((node:any)=><Row key={node.id} title={`${node.hostname} · ${node.release}`} detail={`${node.region} · heartbeat ${node.last_heartbeat_at||node.lastHeartbeatAt||'-'}`} status={node.status}/>) } empty="Nenhuma instância observada."/></Panel>}
    {tab==='Services'&&<Panel title="Dependências e serviços"><List items={(data.services||[]).map((svc:any)=><Row key={svc.id} title={`${svc.service} · ${svc.region}`} detail={`${svc.endpoint||''} · ${svc.version||''}`} status={svc.status}/>) } empty="Nenhum serviço observado."/></Panel>}
    {tab==='Deployments'&&<Panel title="Releases observadas"><List items={(data.deployments||[]).map((d:any)=><Row key={d.id} title={`${d.service} ${d.version}`} detail={`${d.provider} · ${d.replicas||1} réplica(s)`} status={d.status}/>) } empty="Nenhuma release observada."/></Panel>}
    {tab==='Replication'&&<Panel title="Responsabilidade de replicação"><List items={(data.replication||[]).map((r:any)=><Row key={r.resource} title={r.resource} detail={r.status} status={r.configured?'healthy':'pending'}/>) } empty="Nenhuma informação."/></Panel>}
    {tab==='Networking'&&<Panel title="Networking"><pre className="overflow-x-auto rounded-md bg-slate-950 p-4 text-xs text-slate-300">{JSON.stringify(data.networking||{},null,2)}</pre></Panel>}
    {tab==='Incidents'&&<Panel title="Incident log"><IncidentPanel items={data.incidents||[]} onChanged={refresh}/></Panel>}
  </div>;
};

const IncidentPanel:React.FC<{items:any[];onChanged:()=>Promise<void>}>=({items,onChanged})=>{const[title,setTitle]=useState('');const create=async()=>{if(!title.trim())return;await json('/api/infrastructure/incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.trim(),severity:'minor'})});setTitle('');await onChanged();};return <div className="space-y-4"><div className="flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Novo incidente" className="flex-1 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100"/><button onClick={()=>void create()} className="rounded-lg bg-purple-600 px-3 py-2 text-sm font-semibold text-white">Registrar</button></div><List items={items.map((i:any)=><div key={i.id} className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950/60 p-3"><div><p className="text-sm font-medium text-slate-100">{i.title}</p><p className="text-xs text-slate-500">{i.severity} · {i.summary||'sem resumo'}</p></div><div className="flex items-center gap-2"><StatusBadge status={i.status}/>{i.status!=='resolved'&&<button onClick={()=>void json(`/api/infrastructure/incidents/${i.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'resolved'})}).then(onChanged)} className="rounded border border-slate-700 px-2 py-1 text-xs text-slate-300">Resolver</button>}</div></div>)} empty="Nenhum incidente."/></div>};
const Panel:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="mb-4 font-semibold text-slate-100">{title}</h2>{children}</section>;
const List:React.FC<{items:React.ReactNode[];empty:string}>=({items,empty})=><div className="space-y-3">{items.length?items:<p className="text-sm text-slate-500">{empty}</p>}</div>;
const Row:React.FC<{title:string;detail:string;status:string}>=({title,detail,status})=><div className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950/60 p-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-100">{title}</p><p className="truncate text-xs text-slate-500">{detail}</p></div><StatusBadge status={status}/></div>;
