import { useEffect, useMemo, useState } from 'react';
import { Activity, Boxes, CheckCircle2, Cloud, Database, ExternalLink, KeyRound, Loader2, Plus, Rocket, Server, ShieldCheck, Trash2, Zap } from 'lucide-react';

type Service={id:string;name:string;category:string;description:string;mode:string};
type Resource={id:string;service:string;name:string;status:string;plan:string;region?:string|null;endpoint?:string|null;public_url?:string|null};
type Provider={id:string;name:string;type:string;mode:string;region?:string|null;status:string};

const iconMap:Record<string,any>={postgresql:Database,redis:Zap,storage:Cloud,containers:Boxes,deploy:Rocket,domains:ExternalLink,backups:ShieldCheck,logs:Activity,monitoring:Activity,email:Server,webhooks:ExternalLink,ai:Zap};

async function api(path:string,options?:RequestInit){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options?.headers||{})}});if(!r.ok){const body=await r.json().catch(()=>({}));throw new Error(body?.error?.message||'Falha na operação.');}return r.json();}

export function InfrastructureCenter(){
 const [catalog,setCatalog]=useState<Service[]>([]); const [resources,setResources]=useState<Resource[]>([]); const [providers,setProviders]=useState<Provider[]>([]);
 const [usage,setUsage]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState('');
 const [providerOpen,setProviderOpen]=useState(false); const [providerName,setProviderName]=useState(''); const [providerType,setProviderType]=useState('hetzner');

 const load=async()=>{setLoading(true);setError('');try{const [cat,res,pro,us]=await Promise.all([api('/api/control-plane/catalog'),api('/api/control-plane/resources'),api('/api/control-plane/providers'),api('/api/control-plane/usage')]);setCatalog(cat);setResources(res);setProviders(pro);setUsage(us);}catch(e:any){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const active=useMemo(()=>new Set(resources.filter(r=>r.status!=='deleted').map(r=>r.service)),[resources]);
 const activate=async(service:string)=>{setBusy(service);setError('');try{await api('/api/control-plane/resources',{method:'POST',body:JSON.stringify({service,plan:'standard'})});await load();}catch(e:any){setError(e.message);}finally{setBusy(null);}};
 const remove=async(id:string)=>{setBusy(id);try{await api('/api/control-plane/resources/'+id,{method:'DELETE'});await load();}catch(e:any){setError(e.message);}finally{setBusy(null);}};
 const addProvider=async()=>{setBusy('provider');try{await api('/api/control-plane/providers',{method:'POST',body:JSON.stringify({name:providerName,type:providerType,mode:'byok'})});setProviderName('');setProviderOpen(false);await load();}catch(e:any){setError(e.message);}finally{setBusy(null);}};

 return <div className="min-h-screen bg-slate-950 p-6 text-slate-100">
  <div className="mx-auto max-w-7xl space-y-6">
   <header className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
    <div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-300"><Server size={14}/> Control Plane</div><h1 className="text-3xl font-semibold tracking-tight">Central de Infraestrutura</h1><p className="mt-1 text-sm text-slate-400">Ative somente o que seu projeto precisa. A BrisaBase centraliza provisionamento, credenciais, deploy e operação.</p></div>
    <button onClick={()=>setProviderOpen(v=>!v)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4 py-2.5 text-sm font-medium hover:bg-slate-800"><Plus size={17}/> Conectar provedor</button>
   </header>
   {error&&<div className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</div>}
   {providerOpen&&<div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="grid gap-3 md:grid-cols-[1fr_220px_auto]"><input value={providerName} onChange={e=>setProviderName(e.target.value)} placeholder="Nome do provedor" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 outline-none"/><select value={providerType} onChange={e=>setProviderType(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2"><option value="hetzner">Hetzner</option><option value="aws">AWS</option><option value="neon">Neon</option><option value="custom">Outro</option></select><button onClick={addProvider} disabled={!providerName||busy==='provider'} className="rounded-xl bg-cyan-500 px-4 py-2 font-medium text-slate-950 disabled:opacity-50">{busy==='provider'?<Loader2 className="animate-spin"/>:'Salvar'}</button></div></div>}
   <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Serviços ativos" value={String(active.size)} icon={<Boxes/>}/><Stat label="Recursos" value={String(resources.length)} icon={<Server/>}/><Stat label="Provedores" value={String(providers.length)} icon={<Cloud/>}/><Stat label="Uso medido" value={String(usage.length)} icon={<Activity/>}/></section>
   <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Serviços</h2><p className="text-sm text-slate-500">Arquitetura modular: nada é ativado sem necessidade.</p></div></div>
    {loading?<div className="grid place-items-center rounded-2xl border border-slate-800 bg-slate-900 p-12"><Loader2 className="animate-spin text-cyan-400"/></div>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{catalog.map(s=>{const Icon=iconMap[s.id]||Server;const isActive=active.has(s.id);const res=resources.find(r=>r.service===s.id&&r.status!=='deleted');return <div key={s.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4 shadow-lg shadow-black/10"><div className="flex items-start justify-between"><div className="flex gap-3"><div className="rounded-xl bg-slate-800 p-2.5 text-cyan-300"><Icon size={19}/></div><div><div className="font-medium">{s.name}</div><div className="text-xs uppercase tracking-wide text-slate-500">{s.category}</div></div></div><span className={`rounded-full px-2 py-1 text-[11px] ${isActive?'bg-emerald-400/10 text-emerald-300':'bg-slate-800 text-slate-400'}`}>{isActive?'Ativo':'Disponível'}</span></div><p className="mt-4 min-h-10 text-sm text-slate-400">{s.description}</p>{res&&<div className="mt-3 rounded-xl bg-slate-950 p-3 text-xs text-slate-400"><div className="flex justify-between"><span>{res.name}</span><span className="text-emerald-300">{res.status}</span></div>{res.endpoint&&<div className="mt-1 truncate">{res.endpoint}</div>}</div>}<div className="mt-4 flex gap-2">{isActive?<button onClick={()=>res&&remove(res.id)} disabled={!res||busy===res?.id} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-xs hover:bg-slate-800 disabled:opacity-50"><Trash2 size={14}/> Desativar</button>:<button onClick={()=>activate(s.id)} disabled={busy===s.id} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-3 py-2 text-xs font-semibold text-slate-950 disabled:opacity-50">{busy===s.id?<Loader2 size={14} className="animate-spin"/>:<Plus size={14}/>} Ativar</button>}</div></div>})}</div>}
   </section>
   <section className="grid gap-4 lg:grid-cols-2">
    <Panel title="Provedores e BYOK"><div className="space-y-2">{providers.length===0?<Empty text="Nenhum provedor conectado."/>:providers.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl bg-slate-950 p-3"><div><div className="text-sm font-medium">{p.name}</div><div className="text-xs text-slate-500">{p.type} · {p.mode}{p.region?' · '+p.region:''}</div></div><CheckCircle2 size={17} className="text-emerald-400"/></div>)}</div><div className="mt-3 rounded-xl border border-slate-800 p-3 text-xs text-slate-500"><KeyRound size={14} className="mb-1 text-cyan-300"/> Chaves de terceiros são armazenadas cifradas e nunca retornadas pela API de listagem.</div></Panel>
    <Panel title="Uso e operação"><div className="space-y-2">{usage.length===0?<Empty text="O medidor ainda não recebeu eventos."/>:usage.map((u,i)=><div key={i} className="flex justify-between rounded-xl bg-slate-950 p-3 text-sm"><span>{u.service} · {u.metric}</span><span>{u.quantity} {u.unit}</span></div>)}</div><div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Activity size={14}/> Janela de medição: últimos 30 dias.</div></Panel>
   </section>
  </div>
 </div>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:any}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="mb-3 text-cyan-300">{icon}</div><div className="text-2xl font-semibold">{value}</div><div className="text-xs text-slate-500">{label}</div></div>}
function Panel({title,children}:{title:string;children:any}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="mb-4 font-semibold">{title}</h2>{children}</div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-slate-800 p-6 text-center text-sm text-slate-500">{text}</div>}
