import crypto from 'node:crypto';
import { config } from '../config';

function b64url(buf:Buffer):string{return buf.toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
function fromB64url(value:string):Buffer{let s=value.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64');}
function expectedRpId():string{return (process.env.AUTH_WEBAUTHN_RP_ID||new URL(config.appUrl).hostname).trim();}
function expectedOrigins():string[]{const env=String(process.env.AUTH_WEBAUTHN_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);return env.length?env:[new URL(config.appUrl).origin,...config.corsAllowedOrigins].filter((x,i,a)=>a.indexOf(x)===i);}
export function webauthnConfig(){return{rpId:expectedRpId(),rpName:process.env.AUTH_WEBAUTHN_RP_NAME||'BrisaBase',origins:expectedOrigins()};}
export function randomChallenge():string{return b64url(crypto.randomBytes(32));}

function readLength(buf:Buffer,offset:number,ai:number):{length:number;offset:number}{if(ai<24)return{length:ai,offset};if(ai===24)return{length:buf[offset],offset:offset+1};if(ai===25)return{length:buf.readUInt16BE(offset),offset:offset+2};if(ai===26)return{length:buf.readUInt32BE(offset),offset:offset+4};throw new Error('Unsupported CBOR length.');}
function decodeCbor(buf:Buffer,offset=0):{value:any;offset:number}{const first=buf[offset++];const major=first>>5,ai=first&31;let l;if(major===0||major===1){l=readLength(buf,offset,ai);return{value:major===0?l.length:-1-l.length,offset:l.offset};}if(major===2||major===3){l=readLength(buf,offset,ai);const end=l.offset+l.length;if(end>buf.length)throw new Error('Invalid CBOR.');return{value:major===2?buf.subarray(l.offset,end):buf.subarray(l.offset,end).toString('utf8'),offset:end};}if(major===4){l=readLength(buf,offset,ai);const arr=[];offset=l.offset;for(let i=0;i<l.length;i++){const x=decodeCbor(buf,offset);arr.push(x.value);offset=x.offset;}return{value:arr,offset};}if(major===5){l=readLength(buf,offset,ai);const map=new Map<any,any>();offset=l.offset;for(let i=0;i<l.length;i++){const k=decodeCbor(buf,offset);const v=decodeCbor(buf,k.offset);map.set(k.value,v.value);offset=v.offset;}return{value:map,offset};}if(major===7&&ai===20)return{value:false,offset};if(major===7&&ai===21)return{value:true,offset};if(major===7&&ai===22)return{value:null,offset};throw new Error('Unsupported CBOR value.');}
function coseToJwk(cose:Map<any,any>):Record<string,any>{const kty=cose.get(1),alg=cose.get(3);if(kty===2&&alg===-7&&cose.get(-1)===1){return{kty:'EC',crv:'P-256',x:b64url(cose.get(-2)),y:b64url(cose.get(-3)),alg:'ES256',use:'sig'};}if(kty===3&&alg===-257){return{kty:'RSA',n:b64url(cose.get(-1)),e:b64url(cose.get(-2)),alg:'RS256',use:'sig'};}throw new Error('Unsupported passkey public key algorithm.');}
function parseClientData(value:string,expectedType:'webauthn.create'|'webauthn.get',challenge:string){const raw=fromB64url(value);const data=JSON.parse(raw.toString('utf8'));if(data.type!==expectedType||data.challenge!==challenge)throw new Error('WebAuthn challenge is invalid.');if(!expectedOrigins().includes(data.origin))throw new Error('WebAuthn origin is not allowed.');return raw;}
function verifyAuthDataPrefix(authData:Buffer):{flags:number;counter:number}{if(authData.length<37)throw new Error('Authenticator data is invalid.');const expected=crypto.createHash('sha256').update(expectedRpId()).digest();if(!crypto.timingSafeEqual(authData.subarray(0,32),expected))throw new Error('WebAuthn RP ID does not match.');const flags=authData[32];if((flags&0x01)===0)throw new Error('User presence was not verified.');if((flags&0x04)===0)throw new Error('User verification is required for passkeys.');return{flags,counter:authData.readUInt32BE(33)};}

export function registrationOptions(user:{id:string;email:string;displayName:string},challenge:string,existingCredentialIds:string[]=[]){const cfg=webauthnConfig();return{challenge,rp:{id:cfg.rpId,name:cfg.rpName},user:{id:b64url(Buffer.from(user.id)),name:user.email,displayName:user.displayName},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],timeout:60000,attestation:'none',authenticatorSelection:{residentKey:'preferred',userVerification:'required'},excludeCredentials:existingCredentialIds.map(id=>({type:'public-key',id,transports:['internal','hybrid']}))};}
export function verifyRegistration(response:any,challenge:string):{credentialId:string;publicKeyJwk:Record<string,any>;signCount:number;transports:string[]}{if(!response?.id||!response?.response?.clientDataJSON||!response?.response?.attestationObject)throw new Error('Incomplete passkey registration response.');parseClientData(response.response.clientDataJSON,'webauthn.create',challenge);const att=decodeCbor(fromB64url(response.response.attestationObject)).value as Map<any,any>;const authData=att.get('authData') as Buffer;if(!Buffer.isBuffer(authData))throw new Error('Attestation object is missing authenticator data.');const {flags,counter}=verifyAuthDataPrefix(authData);if((flags&0x40)===0)throw new Error('Attested credential data is missing.');let offset=37+16;const credentialLength=authData.readUInt16BE(offset);offset+=2;const credentialId=authData.subarray(offset,offset+credentialLength);offset+=credentialLength;const cose=decodeCbor(authData,offset).value as Map<any,any>;return{credentialId:b64url(credentialId),publicKeyJwk:coseToJwk(cose),signCount:counter,transports:Array.isArray(response.response.transports)?response.response.transports:[]};}

export function authenticationOptions(challenge:string,credentialIds:string[]=[]){return{challenge,rpId:expectedRpId(),timeout:60000,userVerification:'required',allowCredentials:credentialIds.map(id=>({type:'public-key',id,transports:['internal','hybrid']}))};}
export function verifyAuthentication(response:any,challenge:string,stored:{credentialId:string;publicKeyJwk:Record<string,any>;signCount:number}):number{if(!response?.id||response.id!==stored.credentialId||!response?.response?.clientDataJSON||!response?.response?.authenticatorData||!response?.response?.signature)throw new Error('Incomplete passkey authentication response.');const clientRaw=parseClientData(response.response.clientDataJSON,'webauthn.get',challenge);const authData=fromB64url(response.response.authenticatorData);const {counter}=verifyAuthDataPrefix(authData);const signed=Buffer.concat([authData,crypto.createHash('sha256').update(clientRaw).digest()]);const key=crypto.createPublicKey({key:stored.publicKeyJwk as any,format:'jwk'});const alg=stored.publicKeyJwk.kty==='RSA'?'RSA-SHA256':'sha256';if(!crypto.verify(alg,signed,key,fromB64url(response.response.signature)))throw new Error('Passkey signature is invalid.');if(stored.signCount>0&&counter>0&&counter<=stored.signCount)throw new Error('Passkey signature counter did not advance.');return counter;}
