import { createHash, randomBytes, randomUUID } from 'node:crypto';
import dns from 'node:dns/promises';
import net from 'node:net';
import { postgres } from '../db/postgres';
import { controlRepository } from '../db/controlRepository';
import { decryptSecret, encryptSecret } from '../auth/cryptoUtils';
import { emailService } from '../auth/emailService';
import { smsService } from '../auth/smsService';
import { messagingEngine } from './messagingEngine';
import { realStorageEngine } from '../storage/realStorageEngine';

export type AdvancedContext = {
  organizationId: string;
  projectId: string;
  environmentId: string;
  userId?: string;
  role?: string;
  requestId?: string;
  ip?: string;
  userAgent?: string;
};

const id = (prefix: string) => `${prefix}_${randomUUID().replace(/-/g, '').slice(0, 20)}`;
const KEY_RE = /^[A-Za-z][A-Za-z0-9_.-]{0,159}$/;
const MAX_EVENT_BATCH = 100;
const MAX_SEARCH_DOCS_PER_UPSERT = 100;
const MAX_ANALYTICS_QUERY_EVENTS = 50_000;
const MAX_AI_RESPONSE = 2_000_000;
const MAX_VECTOR_SCAN_DOCUMENTS = 500;
const clampRetentionDays = (value: unknown, fallback: number) => Math.min(Math.max(Math.floor(Number(value) || fallback), 7), 730);

function requireManage(ctx: AdvancedContext): void {
  if (!['owner', 'admin', 'developer', 'service'].includes(String(ctx.role || ''))) throw new Error('This operation requires a project management role.');
}
function normalizeKey(value: unknown, label = 'Key'): string {
  const key = String(value || '').trim();
  if (!KEY_RE.test(key)) throw new Error(`${label} must start with a letter and contain only letters, numbers, dot, dash or underscore.`);
  return key;
}
function jsonObject(value: unknown, label: string): Record<string, unknown> {
  if (value === undefined || value === null) return {};
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be an object.`);
  const text = JSON.stringify(value);
  if (Buffer.byteLength(text) > 64 * 1024) throw new Error(`${label} is too large.`);
  return value as Record<string, unknown>;
}
function normalizePricing(value: unknown): { inputPerMillionUsd: number; outputPerMillionUsd: number } {
  const raw = jsonObject(value, 'AI provider pricing');
  const input = Number(raw.inputPerMillionUsd ?? 0);
  const output = Number(raw.outputPerMillionUsd ?? 0);
  if (![input, output].every((item) => Number.isFinite(item) && item >= 0 && item <= 1_000_000)) throw new Error('AI provider pricing must contain non-negative input/output prices up to 1000000 USD per million tokens.');
  return { inputPerMillionUsd: input, outputPerMillionUsd: output };
}
function jsonArray(value: unknown, label: string, max = 100): unknown[] {
  if (value === undefined || value === null) return [];
  if (!Array.isArray(value) || value.length > max) throw new Error(`${label} must be an array with at most ${max} items.`);
  const text = JSON.stringify(value);
  if (Buffer.byteLength(text) > 64 * 1024) throw new Error(`${label} is too large.`);
  return value;
}
function valueAt(attributes: Record<string, unknown>, path: string): unknown {
  return path.split('.').reduce<unknown>((current, part) => current && typeof current === 'object' ? (current as any)[part] : undefined, attributes);
}
function ruleMatches(rule: any, attributes: Record<string, unknown>): boolean {
  if (!rule || typeof rule !== 'object') return false;
  const attribute = String(rule.attribute || '').trim();
  if (!attribute) return false;
  const actual = valueAt(attributes, attribute);
  const expected = rule.value;
  switch (String(rule.operator || 'eq')) {
    case 'eq': return actual === expected;
    case 'ne': return actual !== expected;
    case 'in': return Array.isArray(expected) && expected.includes(actual);
    case 'not_in': return Array.isArray(expected) && !expected.includes(actual);
    case 'contains': return Array.isArray(actual) ? actual.includes(expected) : typeof actual === 'string' && actual.includes(String(expected));
    case 'exists': return actual !== undefined && actual !== null;
    case 'gt': return Number(actual) > Number(expected);
    case 'gte': return Number(actual) >= Number(expected);
    case 'lt': return Number(actual) < Number(expected);
    case 'lte': return Number(actual) <= Number(expected);
    default: return false;
  }
}
function rulesMatch(rules: unknown, attributes: Record<string, unknown>): boolean {
  if (!Array.isArray(rules) || rules.length === 0) return true;
  return rules.every((rule) => ruleMatches(rule, attributes));
}
function bucket(salt: string, subjectId: string): number {
  const digest = createHash('sha256').update(`${salt}:${subjectId}`).digest('hex');
  return parseInt(digest.slice(0, 8), 16) % 10_000;
}
function safeDate(value: unknown, fallback = new Date()): Date {
  if (!value) return fallback;
  const parsed = new Date(String(value));
  if (Number.isNaN(parsed.getTime())) throw new Error('Invalid timestamp.');
  if (Math.abs(parsed.getTime() - Date.now()) > 366 * 24 * 60 * 60 * 1000) throw new Error('Event timestamp is outside the accepted one-year window.');
  return parsed;
}
function cosine(a: number[], b: number[]): number {
  if (a.length !== b.length || !a.length) return -1;
  let dot = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i += 1) { dot += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i]; }
  return na && nb ? dot / Math.sqrt(na * nb) : -1;
}
function normalizeEmbedding(value: unknown, dimensions?: number | null): number[] | null {
  if (value === undefined || value === null) return null;
  if (!Array.isArray(value) || !value.length || value.length > 4096) throw new Error('Embedding must be a numeric array with 1 to 4096 dimensions.');
  const result = value.map(Number);
  if (result.some((item) => !Number.isFinite(item) || Math.abs(item) > 1e6)) throw new Error('Embedding contains an invalid numeric value.');
  if (dimensions && result.length !== dimensions) throw new Error(`Embedding must contain exactly ${dimensions} dimensions.`);
  return result;
}
function privateAddress(address: string): boolean {
  if (net.isIPv4(address)) {
    const p = address.split('.').map(Number);
    return p[0] === 10 || p[0] === 127 || p[0] === 0 || (p[0] === 169 && p[1] === 254) || (p[0] === 172 && p[1] >= 16 && p[1] <= 31) || (p[0] === 192 && p[1] === 168) || p[0] >= 224;
  }
  if (net.isIPv6(address)) {
    const v = address.toLowerCase();
    return v === '::1' || v === '::' || v.startsWith('fc') || v.startsWith('fd') || v.startsWith('fe8') || v.startsWith('fe9') || v.startsWith('fea') || v.startsWith('feb');
  }
  return true;
}
async function validateProviderUrl(raw: string): Promise<URL> {
  let url: URL;
  try { url = new URL(raw); } catch { throw new Error('AI provider base URL is invalid.'); }
  if (url.protocol !== 'https:' || url.username || url.password || url.hash) throw new Error('AI provider base URL must use HTTPS and cannot contain credentials or a fragment.');
  const allowedHosts = new Set(String(process.env.AI_PROVIDER_ALLOWED_HOSTS || 'api.openai.com,openrouter.ai,api.groq.com,api.mistral.ai').split(',').map((value)=>value.trim().toLowerCase()).filter(Boolean));
  if (!allowedHosts.has(url.hostname.toLowerCase())) throw new Error('AI provider hostname is not in AI_PROVIDER_ALLOWED_HOSTS.');
  const results = await dns.lookup(url.hostname, { all: true, verbatim: true });
  if (!results.length || results.some((item) => privateAddress(item.address))) throw new Error('AI provider resolves to a private or reserved network.');
  return url;
}
async function audit(ctx: AdvancedContext, action: string, resourceType: string, resourceId?: string, metadata?: Record<string, unknown>): Promise<void> {
  await controlRepository.logAudit({ organization_id: ctx.organizationId, project_id: ctx.projectId, environment_id: ctx.environmentId, user_id: ctx.userId || 'system', action, resource_type: resourceType, resource_id: resourceId, metadata: metadata || {}, ip_address: ctx.ip, user_agent: ctx.userAgent });
}

export class AdvancedPlatformEngine {
  private campaignTimer: NodeJS.Timeout | null = null;
  private retentionTimer: NodeJS.Timeout | null = null;

  public start(): void {
    if (!this.campaignTimer) {
      this.campaignTimer = setInterval(() => void this.processCampaigns(), 5_000);
      this.campaignTimer.unref?.();
    }
    if (!this.retentionTimer) {
      this.retentionTimer = setInterval(() => void this.cleanupRetention(), 6 * 60 * 60 * 1000);
      this.retentionTimer.unref?.();
      void this.cleanupRetention();
    }
  }
  public stop(): void {
    if (this.campaignTimer) clearInterval(this.campaignTimer);
    if (this.retentionTimer) clearInterval(this.retentionTimer);
    this.campaignTimer = null;
    this.retentionTimer = null;
  }

  // Segments / Remote Config / Feature Flags
  public async listSegments(ctx: AdvancedContext): Promise<any[]> { return postgres.query('SELECT id,name,rules,created_at AS "createdAt",updated_at AS "updatedAt" FROM feature_segments WHERE project_id=$1 AND environment_id=$2 ORDER BY name', [ctx.projectId, ctx.environmentId]); }
  public async saveSegment(ctx: AdvancedContext, input: any): Promise<any> {
    requireManage(ctx); const name = String(input.name || '').trim(); if (!name || name.length > 120) throw new Error('Segment name is required.');
    const rules = jsonArray(input.rules, 'Segment rules', 50);
    const row = (await postgres.query<any>(`INSERT INTO feature_segments(id,organization_id,project_id,environment_id,name,rules,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(project_id,environment_id,name) DO UPDATE SET rules=excluded.rules,updated_at=now() RETURNING id,name,rules,created_at AS "createdAt",updated_at AS "updatedAt"`, [id('seg'),ctx.organizationId,ctx.projectId,ctx.environmentId,name,JSON.stringify(rules),ctx.userId || null]))[0];
    await audit(ctx,'feature.segment.saved','feature_segment',row.id); return row;
  }
  public async removeSegment(ctx: AdvancedContext, segmentId: string): Promise<boolean> { requireManage(ctx); const rows=await postgres.query('DELETE FROM feature_segments WHERE id=$1 AND project_id=$2 AND environment_id=$3 RETURNING id',[segmentId,ctx.projectId,ctx.environmentId]); if(rows.length)await audit(ctx,'feature.segment.deleted','feature_segment',segmentId); return rows.length>0; }

  public async listRemoteConfig(ctx: AdvancedContext): Promise<any[]> { return postgres.query(`SELECT id,key,value,description,enabled,conditions,version,created_at AS "createdAt",updated_at AS "updatedAt" FROM remote_config_parameters WHERE project_id=$1 AND environment_id=$2 ORDER BY key`,[ctx.projectId,ctx.environmentId]); }
  public async saveRemoteConfig(ctx: AdvancedContext,input:any):Promise<any>{ requireManage(ctx); const key=normalizeKey(input.key,'Remote Config key'); const conditions=jsonArray(input.conditions,'Remote Config conditions',50); const value=input.value===undefined?null:input.value; if(Buffer.byteLength(JSON.stringify(value))>32*1024)throw new Error('Remote Config value is too large.'); const row=(await postgres.query<any>(`INSERT INTO remote_config_parameters(id,organization_id,project_id,environment_id,key,value,description,enabled,conditions,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(project_id,environment_id,key) DO UPDATE SET value=excluded.value,description=excluded.description,enabled=excluded.enabled,conditions=excluded.conditions,version=remote_config_parameters.version+1,updated_at=now() RETURNING id,key,value,description,enabled,conditions,version,created_at AS "createdAt",updated_at AS "updatedAt"`,[id('rc'),ctx.organizationId,ctx.projectId,ctx.environmentId,key,JSON.stringify(value),input.description?String(input.description).slice(0,1000):null,input.enabled!==false,JSON.stringify(conditions),ctx.userId||null]))[0]; await audit(ctx,'remote_config.saved','remote_config',row.id,{key}); return row; }
  public async removeRemoteConfig(ctx:AdvancedContext,key:string):Promise<boolean>{requireManage(ctx);const rows=await postgres.query('DELETE FROM remote_config_parameters WHERE project_id=$1 AND environment_id=$2 AND key=$3 RETURNING id',[ctx.projectId,ctx.environmentId,key]);if(rows.length)await audit(ctx,'remote_config.deleted','remote_config',String((rows[0] as any).id),{key});return rows.length>0;}

  public async listFlags(ctx:AdvancedContext):Promise<any[]>{return postgres.query(`SELECT id,key,enabled,rollout_basis_points AS "rolloutBasisPoints",rules,payload,created_at AS "createdAt",updated_at AS "updatedAt" FROM feature_flags WHERE project_id=$1 AND environment_id=$2 ORDER BY key`,[ctx.projectId,ctx.environmentId]);}
  public async saveFlag(ctx:AdvancedContext,input:any):Promise<any>{requireManage(ctx);const key=normalizeKey(input.key,'Feature flag key');const rollout=Math.min(Math.max(Math.round(Number(input.rolloutBasisPoints ?? 10000)),0),10000);const rules=jsonArray(input.rules,'Feature flag rules',50);const payload=input.payload===undefined?null:input.payload;if(Buffer.byteLength(JSON.stringify(payload))>32*1024)throw new Error('Feature flag payload is too large.');const row=(await postgres.query<any>(`INSERT INTO feature_flags(id,organization_id,project_id,environment_id,key,enabled,rollout_basis_points,rules,payload,salt,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(project_id,environment_id,key) DO UPDATE SET enabled=excluded.enabled,rollout_basis_points=excluded.rollout_basis_points,rules=excluded.rules,payload=excluded.payload,updated_at=now() RETURNING id,key,enabled,rollout_basis_points AS "rolloutBasisPoints",rules,payload,created_at AS "createdAt",updated_at AS "updatedAt"`,[id('flag'),ctx.organizationId,ctx.projectId,ctx.environmentId,key,input.enabled===true,rollout,JSON.stringify(rules),JSON.stringify(payload),randomBytes(16).toString('hex'),ctx.userId||null]))[0];await audit(ctx,'feature_flag.saved','feature_flag',row.id,{key});return row;}
  public async removeFlag(ctx:AdvancedContext,key:string):Promise<boolean>{requireManage(ctx);const rows=await postgres.query('DELETE FROM feature_flags WHERE project_id=$1 AND environment_id=$2 AND key=$3 RETURNING id',[ctx.projectId,ctx.environmentId,key]);if(rows.length)await audit(ctx,'feature_flag.deleted','feature_flag',String((rows[0] as any).id),{key});return rows.length>0;}

  private async segmentMap(ctx:AdvancedContext):Promise<Map<string,any[]>>{const rows=await postgres.query<any>('SELECT id,rules FROM feature_segments WHERE project_id=$1 AND environment_id=$2',[ctx.projectId,ctx.environmentId]);return new Map(rows.map((row)=>[row.id,Array.isArray(row.rules)?row.rules:[]]));}
  public async evaluateConfig(ctx:AdvancedContext,subjectId:string,attributes:Record<string,unknown>):Promise<{config:Record<string,unknown>;flags:Record<string,unknown>}>{
    const [configs,flags,segments]=await Promise.all([postgres.query<any>('SELECT * FROM remote_config_parameters WHERE project_id=$1 AND environment_id=$2 AND enabled=true ORDER BY key',[ctx.projectId,ctx.environmentId]),postgres.query<any>('SELECT * FROM feature_flags WHERE project_id=$1 AND environment_id=$2 ORDER BY key',[ctx.projectId,ctx.environmentId]),this.segmentMap(ctx)]);
    const matchesSegment=(segmentId:string)=>{const rules=segments.get(segmentId);return rules?rulesMatch(rules,attributes):false;};
    const config:Record<string,unknown>={};
    for(const item of configs){let value=item.value;for(const condition of (Array.isArray(item.conditions)?item.conditions:[])){const matched=condition?.segmentId?matchesSegment(String(condition.segmentId)):rulesMatch(condition?.rules||[],attributes);if(matched){value=condition?.value;break;}}config[item.key]=value;}
    const evaluated:Record<string,unknown>={};
    for(const flag of flags){let enabled=Boolean(flag.enabled);let rollout=Number(flag.rollout_basis_points||0);let payload=flag.payload||null;let reason=enabled?'default':'disabled';if(enabled){for(const rule of (Array.isArray(flag.rules)?flag.rules:[])){const matched=rule?.segmentId?matchesSegment(String(rule.segmentId)):rulesMatch(rule?.rules||[rule],attributes);if(matched){if(rule.enabled!==undefined)enabled=Boolean(rule.enabled);if(rule.rolloutBasisPoints!==undefined)rollout=Math.min(Math.max(Number(rule.rolloutBasisPoints),0),10000);if(rule.payload!==undefined)payload=rule.payload;reason='rule';break;}}if(enabled&&bucket(String(flag.salt),subjectId)>=rollout){enabled=false;reason='rollout';}}evaluated[flag.key]={enabled,payload,reason};}
    return {config,flags:evaluated};
  }

  // Experiments
  public async listExperiments(ctx:AdvancedContext):Promise<any[]>{return postgres.query(`SELECT id,key,status,variants,primary_metric AS "primaryMetric",audience,winner_variant AS "winnerVariant",started_at AS "startedAt",ended_at AS "endedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM experiments WHERE project_id=$1 AND environment_id=$2 ORDER BY created_at DESC`,[ctx.projectId,ctx.environmentId]);}
  public async saveExperiment(ctx:AdvancedContext,input:any):Promise<any>{requireManage(ctx);const key=normalizeKey(input.key,'Experiment key');const variants=jsonArray(input.variants,'Experiment variants',20).map((v:any)=>({key:normalizeKey(v?.key,'Variant key'),weight:Math.max(0,Math.floor(Number(v?.weight||0)))}));if(variants.length<2)throw new Error('An experiment requires at least two variants.');const total=variants.reduce((s,v)=>s+v.weight,0);if(total!==10000)throw new Error('Experiment variant weights must total 10000 basis points.');const audience=jsonObject(input.audience,'Experiment audience');const row=(await postgres.query<any>(`INSERT INTO experiments(id,organization_id,project_id,environment_id,key,status,variants,primary_metric,audience,salt,created_by) VALUES($1,$2,$3,$4,$5,'draft',$6,$7,$8,$9,$10) ON CONFLICT(project_id,environment_id,key) DO UPDATE SET variants=CASE WHEN experiments.status='draft' THEN excluded.variants ELSE experiments.variants END,primary_metric=excluded.primary_metric,audience=excluded.audience,updated_at=now() RETURNING id,key,status,variants,primary_metric AS "primaryMetric",audience,winner_variant AS "winnerVariant",started_at AS "startedAt",ended_at AS "endedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[id('exp'),ctx.organizationId,ctx.projectId,ctx.environmentId,key,JSON.stringify(variants),input.primaryMetric?normalizeKey(input.primaryMetric,'Primary metric'):null,JSON.stringify(audience),randomBytes(16).toString('hex'),ctx.userId||null]))[0];await audit(ctx,'experiment.saved','experiment',row.id,{key});return row;}
  public async setExperimentStatus(ctx:AdvancedContext,experimentId:string,status:string,winnerVariant?:string):Promise<any|null>{requireManage(ctx);if(!['running','paused','completed','cancelled'].includes(status))throw new Error('Invalid experiment status.');const current=(await postgres.query<any>('SELECT * FROM experiments WHERE id=$1 AND project_id=$2 AND environment_id=$3',[experimentId,ctx.projectId,ctx.environmentId]))[0];if(!current)return null;if(status==='running'&&current.status!=='draft'&&current.status!=='paused')throw new Error('Only draft or paused experiments can be started.');if(status==='completed'&&winnerVariant&&!current.variants.some((v:any)=>v.key===winnerVariant))throw new Error('Winner variant is not part of the experiment.');const row=(await postgres.query<any>(`UPDATE experiments SET status=$2,winner_variant=$3,started_at=CASE WHEN $2='running' THEN COALESCE(started_at,now()) ELSE started_at END,ended_at=CASE WHEN $2 IN ('completed','cancelled') THEN now() ELSE ended_at END,updated_at=now() WHERE id=$1 RETURNING id,key,status,variants,primary_metric AS "primaryMetric",audience,winner_variant AS "winnerVariant",started_at AS "startedAt",ended_at AS "endedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[experimentId,status,winnerVariant||null]))[0];await audit(ctx,'experiment.status_changed','experiment',experimentId,{status,winnerVariant});return row;}
  public async assignExperiment(ctx:AdvancedContext,key:string,subjectId:string,attributes:Record<string,unknown>):Promise<any>{const experiment=(await postgres.query<any>('SELECT * FROM experiments WHERE project_id=$1 AND environment_id=$2 AND key=$3 AND status=\'running\'',[ctx.projectId,ctx.environmentId,key]))[0];if(!experiment)return {experimentKey:key,active:false};if(!rulesMatch((experiment.audience as any)?.rules||[],attributes))return {experimentKey:key,active:false,reason:'audience'};const existing=(await postgres.query<any>('SELECT variant FROM experiment_assignments WHERE experiment_id=$1 AND subject_id=$2',[experiment.id,subjectId]))[0];if(existing)return {experimentKey:key,active:true,variant:existing.variant};const point=bucket(experiment.salt,subjectId);let cursor=0;let variant=experiment.variants[experiment.variants.length-1].key;for(const item of experiment.variants){cursor+=Number(item.weight||0);if(point<cursor){variant=item.key;break;}}await postgres.execute('INSERT INTO experiment_assignments(experiment_id,project_id,environment_id,subject_id,variant) VALUES($1,$2,$3,$4,$5) ON CONFLICT(experiment_id,subject_id) DO NOTHING',[experiment.id,ctx.projectId,ctx.environmentId,subjectId,variant]);const final=(await postgres.query<any>('SELECT variant FROM experiment_assignments WHERE experiment_id=$1 AND subject_id=$2',[experiment.id,subjectId]))[0];return {experimentKey:key,active:true,variant:final?.variant||variant};}
  public async experimentMetrics(ctx:AdvancedContext,experimentId:string):Promise<any>{const experiment=(await postgres.query<any>('SELECT * FROM experiments WHERE id=$1 AND project_id=$2 AND environment_id=$3',[experimentId,ctx.projectId,ctx.environmentId]))[0];if(!experiment)return null;const assignments=await postgres.query<any>('SELECT variant,count(*)::int AS subjects FROM experiment_assignments WHERE experiment_id=$1 GROUP BY variant ORDER BY variant',[experimentId]);let conversions:any[]=[];if(experiment.primary_metric){conversions=await postgres.query<any>(`SELECT a.variant,count(DISTINCT e.subject_id)::int AS conversions FROM experiment_assignments a JOIN analytics_events e ON e.project_id=a.project_id AND e.environment_id=a.environment_id AND e.subject_id=a.subject_id AND e.name=$2 WHERE a.experiment_id=$1 GROUP BY a.variant`,[experimentId,experiment.primary_metric]);}const conv=new Map(conversions.map((r)=>[r.variant,Number(r.conversions)]));return {experimentId,primaryMetric:experiment.primary_metric,variants:assignments.map((r)=>({variant:r.variant,subjects:Number(r.subjects),conversions:conv.get(r.variant)||0,conversionRate:Number(r.subjects)?(conv.get(r.variant)||0)/Number(r.subjects):0}))};}

  // Analytics
  public async ingestAnalytics(ctx:AdvancedContext,events:any[],fallbackSubject?:string):Promise<{accepted:number}>{if(!Array.isArray(events)||!events.length||events.length>MAX_EVENT_BATCH)throw new Error(`Analytics accepts 1 to ${MAX_EVENT_BATCH} events per batch.`);await postgres.transaction(async(client)=>{for(const raw of events){const name=normalizeKey(raw?.name,'Event name');const properties=jsonObject(raw?.properties,'Event properties');const userProperties=jsonObject(raw?.userProperties,'User properties');const subjectId=raw?.subjectId?String(raw.subjectId).slice(0,255):fallbackSubject?.slice(0,255)||null;const sessionId=raw?.sessionId?String(raw.sessionId).slice(0,255):null;const occurredAt=safeDate(raw?.occurredAt).toISOString();await client.query('INSERT INTO analytics_events(id,organization_id,project_id,environment_id,name,subject_id,session_id,properties,user_properties,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id('evt'),ctx.organizationId,ctx.projectId,ctx.environmentId,name,subjectId,sessionId,JSON.stringify(properties),JSON.stringify(userProperties),occurredAt]);}});return {accepted:events.length};}
  public async analyticsOverview(ctx:AdvancedContext,days=30):Promise<any>{const since=new Date(Date.now()-Math.min(Math.max(days,1),365)*86400000).toISOString();const [summary,events,daily]=await Promise.all([postgres.query<any>(`SELECT count(*)::int AS events,count(DISTINCT subject_id)::int AS users,count(DISTINCT session_id)::int AS sessions FROM analytics_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3`,[ctx.projectId,ctx.environmentId,since]),postgres.query<any>(`SELECT name,count(*)::int AS count,count(DISTINCT subject_id)::int AS users FROM analytics_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3 GROUP BY name ORDER BY count DESC LIMIT 100`,[ctx.projectId,ctx.environmentId,since]),postgres.query<any>(`SELECT date_trunc('day',occurred_at) AS day,count(*)::int AS events,count(DISTINCT subject_id)::int AS users FROM analytics_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3 GROUP BY 1 ORDER BY 1`,[ctx.projectId,ctx.environmentId,since])]);return {since,summary:summary[0]||{events:0,users:0,sessions:0},events,daily};}
  public async analyticsFunnel(ctx:AdvancedContext,names:string[],days=30):Promise<any>{if(!Array.isArray(names)||names.length<2||names.length>10)throw new Error('A funnel requires 2 to 10 event names.');const eventNames=names.map((name)=>normalizeKey(name,'Funnel event'));const since=new Date(Date.now()-Math.min(Math.max(days,1),90)*86400000).toISOString();const rows=await postgres.query<any>(`SELECT subject_id,name,occurred_at FROM analytics_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3 AND subject_id IS NOT NULL AND name=ANY($4::text[]) ORDER BY subject_id,occurred_at LIMIT ${MAX_ANALYTICS_QUERY_EVENTS}`,[ctx.projectId,ctx.environmentId,since,eventNames]);const bySubject=new Map<string,any[]>();for(const row of rows){const list=bySubject.get(row.subject_id)||[];list.push(row);bySubject.set(row.subject_id,list);}const counts=new Array(eventNames.length).fill(0);for(const list of bySubject.values()){let cursor=-Infinity;for(let i=0;i<eventNames.length;i++){const match=list.find((item)=>item.name===eventNames[i]&&Date.parse(item.occurred_at)>=cursor);if(!match)break;counts[i]+=1;cursor=Date.parse(match.occurred_at);}}return {since,steps:eventNames.map((name,index)=>({name,subjects:counts[index],conversionFromStart:counts[0]?counts[index]/counts[0]:0}))};}

  public async analyticsRetention(ctx:AdvancedContext,firstEvent:string,returnEvent:string,days=30):Promise<any>{const first=normalizeKey(firstEvent,'First retention event');const returning=normalizeKey(returnEvent,'Return retention event');const windowDays=Math.min(Math.max(Math.floor(Number(days)||30),2),90);const since=new Date(Date.now()-windowDays*86400000).toISOString();const rows=await postgres.query<any>(`SELECT subject_id,name,occurred_at FROM analytics_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3 AND subject_id IS NOT NULL AND name=ANY($4::text[]) ORDER BY subject_id,occurred_at LIMIT ${MAX_ANALYTICS_QUERY_EVENTS}`,[ctx.projectId,ctx.environmentId,since,[first,returning]]);const subjects=new Map<string,{first:number|null;returns:number[]}>();for(const row of rows){const item=subjects.get(row.subject_id)||{first:null,returns:[]};const timestamp=Date.parse(row.occurred_at);if(row.name===first&&(item.first===null||timestamp<item.first))item.first=timestamp;if(row.name===returning)item.returns.push(timestamp);subjects.set(row.subject_id,item);}const cohorts=new Map<string,{subjects:number;d1:number;d7:number;d30:number}>();for(const item of subjects.values()){if(item.first===null)continue;const cohort=new Date(item.first).toISOString().slice(0,10);const bucket=cohorts.get(cohort)||{subjects:0,d1:0,d7:0,d30:0};bucket.subjects+=1;const daysSeen=new Set(item.returns.filter((timestamp)=>timestamp>item.first!).map((timestamp)=>Math.floor((timestamp-item.first!)/86400000)));if(daysSeen.has(1))bucket.d1+=1;if(daysSeen.has(7))bucket.d7+=1;if(daysSeen.has(30))bucket.d30+=1;cohorts.set(cohort,bucket);}return {since,firstEvent:first,returnEvent:returning,cohorts:[...cohorts.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([cohort,item])=>({cohort,...item,d1Rate:item.subjects?item.d1/item.subjects:0,d7Rate:item.subjects?item.d7/item.subjects:0,d30Rate:item.subjects?item.d30/item.subjects:0}))};}

  // App Quality / Distribution
  public async ingestQuality(ctx:AdvancedContext,events:any[],fallbackSubject?:string):Promise<{accepted:number}>{if(!Array.isArray(events)||!events.length||events.length>MAX_EVENT_BATCH)throw new Error(`App Quality accepts 1 to ${MAX_EVENT_BATCH} events per batch.`);const allowed=new Set(['crash','error','anr','performance','trace']);await postgres.transaction(async(client)=>{for(const raw of events){const kind=String(raw?.kind||'');if(!allowed.has(kind))throw new Error('Invalid App Quality event kind.');const name=String(raw?.name||'').trim().slice(0,200);if(!name)throw new Error('App Quality event name is required.');const stack=raw?.stack?String(raw.stack).slice(0,64*1024):null;const message=raw?.message?String(raw.message).slice(0,16*1024):null;const duration=raw?.durationMs===undefined?null:Number(raw.durationMs);if(duration!==null&&(!Number.isFinite(duration)||duration<0||duration>86_400_000))throw new Error('Invalid performance duration.');await client.query('INSERT INTO app_quality_events(id,organization_id,project_id,environment_id,kind,release,platform,severity,name,message,stack,duration_ms,subject_id,metadata,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[id('quality'),ctx.organizationId,ctx.projectId,ctx.environmentId,kind,raw?.release?String(raw.release).slice(0,120):null,raw?.platform?String(raw.platform).slice(0,40):null,['info','warning','error','fatal'].includes(String(raw?.severity))?String(raw.severity):(kind==='performance'||kind==='trace'?'info':'error'),name,message,stack,duration,raw?.subjectId?String(raw.subjectId).slice(0,255):fallbackSubject?.slice(0,255)||null,JSON.stringify(jsonObject(raw?.metadata,'Quality metadata')),safeDate(raw?.occurredAt).toISOString()]);}});return {accepted:events.length};}
  public async qualityOverview(ctx:AdvancedContext,days=30):Promise<any>{const since=new Date(Date.now()-Math.min(Math.max(days,1),90)*86400000).toISOString();const [byKind,byRelease,performance]=await Promise.all([postgres.query<any>(`SELECT kind,count(*)::int AS count,count(DISTINCT subject_id)::int AS users FROM app_quality_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3 GROUP BY kind ORDER BY count DESC`,[ctx.projectId,ctx.environmentId,since]),postgres.query<any>(`SELECT coalesce(release,'unknown') AS release,count(*) FILTER(WHERE kind IN ('crash','anr'))::int AS crashes,count(*) FILTER(WHERE kind='error')::int AS errors,count(DISTINCT subject_id) FILTER(WHERE kind IN ('crash','anr'))::int AS affected_users FROM app_quality_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3 GROUP BY release ORDER BY crashes DESC,errors DESC LIMIT 50`,[ctx.projectId,ctx.environmentId,since]),postgres.query<any>(`SELECT name,count(*)::int AS samples,round(avg(duration_ms)::numeric,2)::float8 AS avg_ms,percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms)::float8 AS p95_ms FROM app_quality_events WHERE project_id=$1 AND environment_id=$2 AND occurred_at>=$3 AND duration_ms IS NOT NULL GROUP BY name ORDER BY p95_ms DESC LIMIT 100`,[ctx.projectId,ctx.environmentId,since])]);return {since,byKind,byRelease,performance};}
  public async listQualityEvents(ctx:AdvancedContext,limit=200):Promise<any[]>{return postgres.query(`SELECT id,kind,release,platform,severity,name,message,duration_ms AS "durationMs",subject_id AS "subjectId",metadata,occurred_at AS "occurredAt" FROM app_quality_events WHERE project_id=$1 AND environment_id=$2 ORDER BY occurred_at DESC LIMIT $3`,[ctx.projectId,ctx.environmentId,Math.min(Math.max(limit,1),1000)]);}
  public async listDistribution(ctx:AdvancedContext):Promise<any[]>{return postgres.query(`SELECT id,version,platform,storage_bucket AS "storageBucket",storage_path AS "storagePath",notes,status,created_at AS "createdAt" FROM app_distribution_releases WHERE project_id=$1 AND environment_id=$2 ORDER BY created_at DESC`,[ctx.projectId,ctx.environmentId]);}
  public async createDistribution(ctx:AdvancedContext,input:any):Promise<any>{requireManage(ctx);const version=String(input.version||'').trim().slice(0,120);const platform=String(input.platform||'').trim().slice(0,40);if(!version||!platform)throw new Error('Release version and platform are required.');let bucketName:string|null=null,path:string|null=null;if(input.storageBucket||input.storagePath){bucketName=String(input.storageBucket||'').trim();path=String(input.storagePath||'').trim();if(!bucketName||!path)throw new Error('Both storageBucket and storagePath are required.');const found=await realStorageEngine.object({...ctx,role:'admin'} as any,bucketName,path);if(!found)throw new Error('App Distribution artifact was not found in Storage.');}const row=(await postgres.query<any>(`INSERT INTO app_distribution_releases(id,organization_id,project_id,environment_id,version,platform,storage_bucket,storage_path,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,version,platform,storage_bucket AS "storageBucket",storage_path AS "storagePath",notes,status,created_at AS "createdAt"`,[id('release'),ctx.organizationId,ctx.projectId,ctx.environmentId,version,platform,bucketName,path,input.notes?String(input.notes).slice(0,10000):null,ctx.userId||null]))[0];await audit(ctx,'app_distribution.created','app_release',row.id,{version,platform});return row;}

  // Search / Vector
  public async listSearchIndexes(ctx:AdvancedContext):Promise<any[]>{return postgres.query(`SELECT i.id,i.key,i.dimensions,i.metadata,i.created_at AS "createdAt",i.updated_at AS "updatedAt",count(d.id)::int AS documents FROM search_indexes i LEFT JOIN search_documents d ON d.index_id=i.id WHERE i.project_id=$1 AND i.environment_id=$2 GROUP BY i.id ORDER BY i.key`,[ctx.projectId,ctx.environmentId]);}
  public async saveSearchIndex(ctx:AdvancedContext,input:any):Promise<any>{requireManage(ctx);const key=normalizeKey(input.key,'Search index key');const dimensions=input.dimensions===undefined||input.dimensions===null?null:Math.floor(Number(input.dimensions));if(dimensions!==null&&(dimensions<1||dimensions>4096))throw new Error('Search vector dimensions must be between 1 and 4096.');const row=(await postgres.query<any>(`INSERT INTO search_indexes(id,organization_id,project_id,environment_id,key,dimensions,metadata,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(project_id,environment_id,key) DO UPDATE SET dimensions=CASE WHEN NOT EXISTS(SELECT 1 FROM search_documents WHERE index_id=search_indexes.id) THEN excluded.dimensions ELSE search_indexes.dimensions END,metadata=excluded.metadata,updated_at=now() RETURNING id,key,dimensions,metadata,created_at AS "createdAt",updated_at AS "updatedAt"`,[id('sidx'),ctx.organizationId,ctx.projectId,ctx.environmentId,key,dimensions,JSON.stringify(jsonObject(input.metadata,'Index metadata')),ctx.userId||null]))[0];await audit(ctx,'search.index.saved','search_index',row.id,{key});return row;}
  public async upsertSearchDocuments(ctx:AdvancedContext,indexKey:string,documents:any[]):Promise<{upserted:number}>{requireManage(ctx);if(!Array.isArray(documents)||!documents.length||documents.length>MAX_SEARCH_DOCS_PER_UPSERT)throw new Error(`Search accepts 1 to ${MAX_SEARCH_DOCS_PER_UPSERT} documents per batch.`);const index=(await postgres.query<any>('SELECT * FROM search_indexes WHERE project_id=$1 AND environment_id=$2 AND key=$3',[ctx.projectId,ctx.environmentId,indexKey]))[0];if(!index)throw new Error('Search index not found.');let expectedDimensions=index.dimensions?Number(index.dimensions):null;for(const raw of documents){if(raw?.embedding!==undefined&&raw?.embedding!==null){const candidate=normalizeEmbedding(raw.embedding,expectedDimensions);if(!expectedDimensions&&candidate){expectedDimensions=candidate.length;}else if(candidate&&expectedDimensions&&candidate.length!==expectedDimensions)throw new Error(`Embedding must contain exactly ${expectedDimensions} dimensions.`);}}await postgres.transaction(async(client)=>{if(!index.dimensions&&expectedDimensions){const existing=await client.query('SELECT 1 FROM search_documents WHERE index_id=$1 LIMIT 1',[index.id]);if(!existing.rows.length)await client.query('UPDATE search_indexes SET dimensions=$2,updated_at=now() WHERE id=$1',[index.id,expectedDimensions]);}for(const raw of documents){const externalId=String(raw?.id||raw?.externalId||'').trim().slice(0,255);const content=String(raw?.content||'');if(!externalId||!content||content.length>1_000_000)throw new Error('Each search document requires id and content up to 1 MB.');const embedding=normalizeEmbedding(raw?.embedding,expectedDimensions);await client.query(`INSERT INTO search_documents(id,index_id,project_id,environment_id,external_id,title,content,metadata,embedding) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(index_id,external_id) DO UPDATE SET title=excluded.title,content=excluded.content,metadata=excluded.metadata,embedding=excluded.embedding,updated_at=now()`,[id('doc'),index.id,ctx.projectId,ctx.environmentId,externalId,raw?.title?String(raw.title).slice(0,10000):null,content,JSON.stringify(jsonObject(raw?.metadata,'Document metadata')),embedding]);}});return {upserted:documents.length};}
  public async deleteSearchDocument(ctx:AdvancedContext,indexKey:string,externalId:string):Promise<boolean>{requireManage(ctx);const rows=await postgres.query(`DELETE FROM search_documents d USING search_indexes i WHERE d.index_id=i.id AND i.project_id=$1 AND i.environment_id=$2 AND i.key=$3 AND d.external_id=$4 RETURNING d.id`,[ctx.projectId,ctx.environmentId,indexKey,externalId]);return rows.length>0;}
  public async search(ctx:AdvancedContext,indexKey:string,input:any):Promise<any>{const index=(await postgres.query<any>('SELECT * FROM search_indexes WHERE project_id=$1 AND environment_id=$2 AND key=$3',[ctx.projectId,ctx.environmentId,indexKey]))[0];if(!index)throw new Error('Search index not found.');const limit=Math.min(Math.max(Number(input?.limit)||20,1),100);const query=String(input?.query||'').trim().slice(0,1000);const embedding=normalizeEmbedding(input?.embedding,index.dimensions?Number(index.dimensions):null);const mode=String(input?.mode||'hybrid');const scores=new Map<string,{row:any;textScore:number;vectorScore:number}>();if(query&&(mode==='text'||mode==='hybrid')){const rows=await postgres.query<any>(`SELECT external_id AS id,title,content,metadata,ts_rank(to_tsvector('simple',coalesce(title,'')||' '||content),plainto_tsquery('simple',$4))::float8 AS score FROM search_documents WHERE project_id=$1 AND environment_id=$2 AND index_id=$3 AND to_tsvector('simple',coalesce(title,'')||' '||content) @@ plainto_tsquery('simple',$4) ORDER BY score DESC LIMIT $5`,[ctx.projectId,ctx.environmentId,index.id,query,Math.min(limit*5,500)]);for(const row of rows)scores.set(row.id,{row,textScore:Number(row.score||0),vectorScore:0});}if(embedding&&(mode==='vector'||mode==='hybrid')){const rows=await postgres.query<any>(`SELECT external_id AS id,title,content,metadata,embedding FROM search_documents WHERE project_id=$1 AND environment_id=$2 AND index_id=$3 AND embedding IS NOT NULL ORDER BY updated_at DESC LIMIT ${MAX_VECTOR_SCAN_DOCUMENTS}`,[ctx.projectId,ctx.environmentId,index.id]);for(const row of rows){const vectorScore=cosine(embedding,(row.embedding||[]).map(Number));const existing=scores.get(row.id);if(existing)existing.vectorScore=vectorScore;else scores.set(row.id,{row:{id:row.id,title:row.title,content:row.content,metadata:row.metadata},textScore:0,vectorScore});}}const results=[...scores.values()].map((item)=>({...item.row,textScore:item.textScore,vectorScore:item.vectorScore,score:mode==='text'?item.textScore:mode==='vector'?item.vectorScore:item.textScore*0.35+Math.max(item.vectorScore,0)*0.65})).sort((a,b)=>b.score-a.score).slice(0,limit);return {index:indexKey,mode,results};}

  // AI Gateway (OpenAI-compatible HTTPS providers)
  public async listAiProviders(ctx:AdvancedContext):Promise<any[]>{return postgres.query(`SELECT id,key,base_url AS "baseUrl",model,pricing,enabled,created_at AS "createdAt",updated_at AS "updatedAt" FROM ai_provider_configs WHERE project_id=$1 AND environment_id=$2 ORDER BY key`,[ctx.projectId,ctx.environmentId]);}
  public async saveAiProvider(ctx:AdvancedContext,input:any):Promise<any>{requireManage(ctx);const key=normalizeKey(input.key,'AI provider key');const url=await validateProviderUrl(String(input.baseUrl||''));const model=String(input.model||'').trim().slice(0,160);if(!model)throw new Error('AI provider model is required.');const current=(await postgres.query<any>('SELECT api_key_encrypted FROM ai_provider_configs WHERE project_id=$1 AND environment_id=$2 AND key=$3',[ctx.projectId,ctx.environmentId,key]))[0];const rawKey=input.apiKey?String(input.apiKey):'';if(!rawKey&&!current)throw new Error('AI provider API key is required.');const encrypted=rawKey?encryptSecret(rawKey):current.api_key_encrypted;const row=(await postgres.query<any>(`INSERT INTO ai_provider_configs(id,organization_id,project_id,environment_id,key,base_url,model,api_key_encrypted,pricing,enabled,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(project_id,environment_id,key) DO UPDATE SET base_url=excluded.base_url,model=excluded.model,api_key_encrypted=excluded.api_key_encrypted,pricing=excluded.pricing,enabled=excluded.enabled,updated_at=now() RETURNING id,key,base_url AS "baseUrl",model,pricing,enabled,created_at AS "createdAt",updated_at AS "updatedAt"`,[id('aip'),ctx.organizationId,ctx.projectId,ctx.environmentId,key,url.toString().replace(/\/$/,''),model,encrypted,JSON.stringify(normalizePricing(input.pricing)),input.enabled!==false,ctx.userId||null]))[0];await audit(ctx,'ai.provider.saved','ai_provider',row.id,{key,model});return row;}
  public async removeAiProvider(ctx:AdvancedContext,providerId:string):Promise<boolean>{requireManage(ctx);const rows=await postgres.query('DELETE FROM ai_provider_configs WHERE id=$1 AND project_id=$2 AND environment_id=$3 RETURNING id',[providerId,ctx.projectId,ctx.environmentId]);return rows.length>0;}
  public async aiGenerate(ctx:AdvancedContext,providerKey:string,input:any):Promise<any>{const provider=(await postgres.query<any>('SELECT * FROM ai_provider_configs WHERE project_id=$1 AND environment_id=$2 AND key=$3 AND enabled=true',[ctx.projectId,ctx.environmentId,providerKey]))[0];if(!provider)throw new Error('AI provider not found or disabled.');const base=await validateProviderUrl(provider.base_url);const messages=Array.isArray(input?.messages)?input.messages.slice(0,100).map((m:any)=>({role:['system','user','assistant'].includes(String(m?.role))?String(m.role):'user',content:String(m?.content||'').slice(0,200_000)})):[];if(!messages.length)throw new Error('AI generation requires at least one message.');const endpoint=new URL(base.toString().replace(/\/$/,'')+'/chat/completions');if(endpoint.hostname!==base.hostname)throw new Error('Invalid AI provider endpoint.');const started=Date.now();let status='ok';try{const response=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${decryptSecret(provider.api_key_encrypted)}`,'Content-Type':'application/json'},body:JSON.stringify({model:provider.model,messages,temperature:input?.temperature,max_tokens:input?.maxTokens}),redirect:'error',signal:AbortSignal.timeout(Math.min(Math.max(Number(input?.timeoutMs)||60_000,1_000),120_000))});const text=await response.text();if(Buffer.byteLength(text)>MAX_AI_RESPONSE)throw new Error('AI provider response exceeded the maximum allowed size.');if(!response.ok)throw new Error(`AI provider failed (${response.status}): ${text.slice(0,500)}`);const payload=JSON.parse(text);const usage=payload?.usage||{};const inputTokens=Number(usage.prompt_tokens||usage.input_tokens||0);const outputTokens=Number(usage.completion_tokens||usage.output_tokens||0);const pricing=provider.pricing||{};const costUsd=(inputTokens*Number(pricing.inputPerMillionUsd||0)+outputTokens*Number(pricing.outputPerMillionUsd||0))/1_000_000;await postgres.execute('INSERT INTO ai_usage(id,provider_id,project_id,environment_id,model,input_tokens,output_tokens,latency_ms,cost_usd,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id('aiu'),provider.id,ctx.projectId,ctx.environmentId,provider.model,inputTokens,outputTokens,Date.now()-started,costUsd,'ok']);return {provider:providerKey,model:provider.model,content:payload?.choices?.[0]?.message?.content??null,usage,costUsd,requestId:payload?.id||null};}catch(error){status='error';await postgres.execute('INSERT INTO ai_usage(id,provider_id,project_id,environment_id,model,latency_ms,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[id('aiu'),provider.id,ctx.projectId,ctx.environmentId,provider.model,Date.now()-started,status]).catch(()=>undefined);throw error;}}
  public async aiEmbed(ctx:AdvancedContext,providerKey:string,texts:string[]):Promise<{provider:string;model:string;embeddings:number[][];usage:Record<string,unknown>;costUsd:number}>{if(!Array.isArray(texts)||!texts.length||texts.length>100)throw new Error('Embedding request must contain 1 to 100 texts.');const provider=(await postgres.query<any>('SELECT * FROM ai_provider_configs WHERE project_id=$1 AND environment_id=$2 AND key=$3 AND enabled=true',[ctx.projectId,ctx.environmentId,providerKey]))[0];if(!provider)throw new Error('AI provider not found or disabled.');const base=await validateProviderUrl(provider.base_url);const endpoint=new URL(base.toString().replace(/\/$/,'')+'/embeddings');const clean=texts.map((text)=>String(text||'').slice(0,100_000));const started=Date.now();try{const response=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${decryptSecret(provider.api_key_encrypted)}`,'Content-Type':'application/json'},body:JSON.stringify({model:provider.model,input:clean}),redirect:'error',signal:AbortSignal.timeout(60_000)});const raw=await response.text();if(Buffer.byteLength(raw)>MAX_AI_RESPONSE)throw new Error('AI provider response exceeded the maximum allowed size.');if(!response.ok)throw new Error(`AI embedding provider failed (${response.status}): ${raw.slice(0,500)}`);const payload=JSON.parse(raw);const embeddings=(Array.isArray(payload?.data)?payload.data:[]).map((item:any)=>normalizeEmbedding(item?.embedding)||[]);if(embeddings.length!==clean.length||embeddings.some((item:number[])=>!item.length))throw new Error('AI embedding provider returned an invalid embedding payload.');const usage=payload?.usage||{};const inputTokens=Number(usage.prompt_tokens||usage.input_tokens||usage.total_tokens||0);const pricing=provider.pricing||{};const costUsd=inputTokens*Number(pricing.inputPerMillionUsd||0)/1_000_000;await postgres.execute('INSERT INTO ai_usage(id,provider_id,project_id,environment_id,model,input_tokens,output_tokens,latency_ms,cost_usd,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id('aiu'),provider.id,ctx.projectId,ctx.environmentId,provider.model,inputTokens,0,Date.now()-started,costUsd,'ok']);return {provider:providerKey,model:provider.model,embeddings,usage,costUsd};}catch(error){await postgres.execute('INSERT INTO ai_usage(id,provider_id,project_id,environment_id,model,latency_ms,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[id('aiu'),provider.id,ctx.projectId,ctx.environmentId,provider.model,Date.now()-started,'error']).catch(()=>undefined);throw error;}}
  public async rag(ctx:AdvancedContext,input:any):Promise<any>{const query=String(input?.query||'').trim();if(!query||query.length>20_000)throw new Error('RAG query is required and must be at most 20000 characters.');const indexKey=normalizeKey(input?.indexKey,'Search index key');const embeddingProviderKey=normalizeKey(input?.embeddingProviderKey,'Embedding provider key');const chatProviderKey=normalizeKey(input?.chatProviderKey,'Chat provider key');const embedded=await this.aiEmbed(ctx,embeddingProviderKey,[query]);const searchResult=await this.search(ctx,indexKey,{query,embedding:embedded.embeddings[0],mode:'hybrid',limit:Math.min(Math.max(Number(input?.limit)||5,1),20)});const context=(searchResult.results||[]).map((item:any,index:number)=>`[${index+1}] ${item.title||item.id}\n${String(item.content||'').slice(0,12000)}`).join('\n\n');const generated=await this.aiGenerate(ctx,chatProviderKey,{messages:[{role:'system',content:'Answer using only the supplied retrieval context. If the context is insufficient, say so.'},{role:'user',content:`Question:\n${query}\n\nRetrieval context:\n${context}`}],temperature:input?.temperature??0.2,maxTokens:input?.maxTokens});return {...generated,retrieval:{index:indexKey,results:(searchResult.results||[]).map((item:any)=>({id:item.id,title:item.title,score:item.score}))},embeddingUsage:embedded.usage};}
  public async aiUsage(ctx:AdvancedContext,days=30):Promise<any>{const since=new Date(Date.now()-Math.min(Math.max(days,1),365)*86400000).toISOString();const rows=await postgres.query<any>(`SELECT model,count(*)::int AS requests,sum(input_tokens)::int AS input_tokens,sum(output_tokens)::int AS output_tokens,round(sum(cost_usd)::numeric,8)::float8 AS cost_usd,round(avg(latency_ms)::numeric,2)::float8 AS avg_latency_ms,count(*) FILTER(WHERE status='error')::int AS errors FROM ai_usage WHERE project_id=$1 AND environment_id=$2 AND created_at>=$3 GROUP BY model ORDER BY requests DESC`,[ctx.projectId,ctx.environmentId,since]);return {since,models:rows};}

  // Messaging templates / campaigns
  public async listTemplates(ctx:AdvancedContext):Promise<any[]>{return postgres.query(`SELECT id,name,channel,subject,body,created_at AS "createdAt",updated_at AS "updatedAt" FROM messaging_templates WHERE project_id=$1 AND environment_id=$2 ORDER BY name`,[ctx.projectId,ctx.environmentId]);}
  public async saveTemplate(ctx:AdvancedContext,input:any):Promise<any>{requireManage(ctx);const name=String(input.name||'').trim().slice(0,120);const channel=String(input.channel||'');const body=String(input.body||'').trim();if(!name||!['push','email','sms'].includes(channel)||!body||body.length>10000)throw new Error('Template name, channel and body are required.');const row=(await postgres.query<any>(`INSERT INTO messaging_templates(id,organization_id,project_id,environment_id,name,channel,subject,body,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(project_id,environment_id,name,channel) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=now() RETURNING id,name,channel,subject,body,created_at AS "createdAt",updated_at AS "updatedAt"`,[id('mtpl'),ctx.organizationId,ctx.projectId,ctx.environmentId,name,channel,input.subject?String(input.subject).slice(0,255):null,body,ctx.userId||null]))[0];return row;}
  public async listCampaigns(ctx:AdvancedContext):Promise<any[]>{return postgres.query(`SELECT id,name,channel,template_id AS "templateId",subject,body,audience,status,scheduled_at AS "scheduledAt",attempted_count AS "attemptedCount",delivered_count AS "deliveredCount",failed_count AS "failedCount",error_message AS "errorMessage",sent_at AS "sentAt",created_at AS "createdAt" FROM messaging_campaigns WHERE project_id=$1 AND environment_id=$2 ORDER BY created_at DESC LIMIT 500`,[ctx.projectId,ctx.environmentId]);}
  public async createCampaign(ctx:AdvancedContext,input:any):Promise<any>{requireManage(ctx);const channel=String(input.channel||'');if(!['push','email','sms'].includes(channel))throw new Error('Campaign channel must be push, email or sms.');const name=String(input.name||'').trim().slice(0,160);let body=String(input.body||'').trim();let subject=input.subject?String(input.subject).slice(0,255):null;let templateId=input.templateId?String(input.templateId):null;if(templateId){const tpl=(await postgres.query<any>('SELECT * FROM messaging_templates WHERE id=$1 AND project_id=$2 AND environment_id=$3 AND channel=$4',[templateId,ctx.projectId,ctx.environmentId,channel]))[0];if(!tpl)throw new Error('Campaign template not found.');body=body||tpl.body;subject=subject||tpl.subject;}if(!name||!body)throw new Error('Campaign name and body are required.');const scheduled=input.scheduledAt?safeDate(input.scheduledAt):null;const status=scheduled&&scheduled.getTime()>Date.now()?'queued':'queued';const row=(await postgres.query<any>(`INSERT INTO messaging_campaigns(id,organization_id,project_id,environment_id,name,channel,template_id,subject,body,audience,status,scheduled_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[id('camp'),ctx.organizationId,ctx.projectId,ctx.environmentId,name,channel,templateId,subject,body,JSON.stringify(jsonObject(input.audience,'Campaign audience')),status,scheduled?.toISOString()||null,ctx.userId||null]))[0];if(!scheduled||scheduled.getTime()<=Date.now())return this.sendCampaign(ctx,row.id);return row;}
  public async cancelCampaign(ctx:AdvancedContext,campaignId:string):Promise<boolean>{requireManage(ctx);const rows=await postgres.query(`UPDATE messaging_campaigns SET status='cancelled',updated_at=now() WHERE id=$1 AND project_id=$2 AND environment_id=$3 AND status='queued' RETURNING id`,[campaignId,ctx.projectId,ctx.environmentId]);return rows.length>0;}
  private async campaignRecipients(ctx:AdvancedContext,audience:any):Promise<any[]>{
    const values:any[]=[ctx.projectId,ctx.environmentId];
    let where="project_id=$1 AND environment_id=$2 AND status='active'";
    if(Array.isArray(audience?.userIds)&&audience.userIds.length){values.push(audience.userIds.slice(0,500));where+=` AND id=ANY($${values.length}::varchar[])`;}
    if(audience?.role){values.push(String(audience.role));where+=` AND role=$${values.length}`;}
    let segmentRules:any[]|null=null;
    if(audience?.segmentId){const segment=(await postgres.query<any>('SELECT rules FROM feature_segments WHERE id=$1 AND project_id=$2 AND environment_id=$3',[String(audience.segmentId),ctx.projectId,ctx.environmentId]))[0];if(!segment)throw new Error('Campaign audience segment was not found.');segmentRules=Array.isArray(segment.rules)?segment.rules:[];}
    if(!segmentRules)return postgres.query<any>(`SELECT id,email,email_verified,phone,phone_verified,display_name,role,user_metadata,app_metadata FROM auth_users WHERE ${where} ORDER BY created_at DESC LIMIT 500`,values);
    const matched:any[]=[];let offset=0;
    while(matched.length<500&&offset<50_000){const batch=await postgres.query<any>(`SELECT id,email,email_verified,phone,phone_verified,display_name,role,user_metadata,app_metadata FROM auth_users WHERE ${where} ORDER BY created_at DESC LIMIT 1000 OFFSET ${offset}`,values);if(!batch.length)break;for(const user of batch){const attrs={id:user.id,email:user.email,phone:user.phone,role:user.role,displayName:user.display_name,userMetadata:user.user_metadata||{},appMetadata:user.app_metadata||{},...(user.user_metadata||{}),...(user.app_metadata||{})};if(rulesMatch(segmentRules,attrs)){matched.push(user);if(matched.length>=500)break;}}offset+=batch.length;if(batch.length<1000)break;}
    return matched;
  }
  public async sendCampaign(ctx:AdvancedContext,campaignId:string):Promise<any>{requireManage(ctx);const row=(await postgres.query<any>(`UPDATE messaging_campaigns SET status='sending',updated_at=now(),error_message=NULL WHERE id=$1 AND project_id=$2 AND environment_id=$3 AND status IN ('queued','draft','failed') RETURNING *`,[campaignId,ctx.projectId,ctx.environmentId]))[0];if(!row){const exists=(await postgres.query<any>('SELECT status FROM messaging_campaigns WHERE id=$1 AND project_id=$2 AND environment_id=$3',[campaignId,ctx.projectId,ctx.environmentId]))[0];if(!exists)throw new Error('Campaign not found.');throw new Error('Campaign cannot be sent from its current status.');}let attempted=0,delivered=0,failed=0;let firstError:string|null=null;try{if(row.channel==='push'){let pushAudience=row.audience||{};if(pushAudience.segmentId){const recipients=await this.campaignRecipients(ctx,pushAudience);pushAudience={...pushAudience,userIds:recipients.map((item:any)=>item.id)};}const msg=await messagingEngine.createMessage({...ctx,role:ctx.role||'admin'} as any,{title:row.subject||row.name,body:row.body,audience:pushAudience});attempted=Number(msg.attemptedCount||0);delivered=Number(msg.deliveredCount||0);failed=Number(msg.failedCount||0);}else{const recipients=await this.campaignRecipients(ctx,row.audience||{});for(const recipient of recipients){if(row.channel==='email'&&!recipient.email_verified)continue;if(row.channel==='sms'&&!recipient.phone_verified)continue;attempted+=1;try{if(row.channel==='email')await emailService.sendEmail({to:recipient.email,subject:row.subject||row.name,body:row.body});else await smsService.sendMessage(recipient.phone,row.body);delivered+=1;}catch(error){failed+=1;firstError=firstError||(error instanceof Error?error.message:String(error));}}}const status=attempted===0||delivered===0?'failed':failed?'partial':'sent';const updated=(await postgres.query<any>(`UPDATE messaging_campaigns SET status=$2,attempted_count=$3,delivered_count=$4,failed_count=$5,error_message=$6,sent_at=now(),updated_at=now() WHERE id=$1 RETURNING *`,[campaignId,status,attempted,delivered,failed,firstError|| (attempted===0?'No eligible recipients matched the campaign audience.':null)]))[0];await audit(ctx,'messaging.campaign.sent','messaging_campaign',campaignId,{attempted,delivered,failed,status});return updated;}catch(error){await postgres.execute("UPDATE messaging_campaigns SET status='failed',error_message=$2,updated_at=now() WHERE id=$1",[campaignId,(error instanceof Error?error.message:String(error)).slice(0,1000)]);throw error;}}
  private async processCampaigns():Promise<void>{await postgres.execute(`UPDATE messaging_campaigns SET status='failed',error_message='Recovered stale sending campaign; retry is available.',updated_at=now() WHERE status='sending' AND updated_at < now() - interval '15 minutes'`).catch(()=>undefined);const rows=await postgres.query<any>(`SELECT * FROM messaging_campaigns WHERE status='queued' AND (scheduled_at IS NULL OR scheduled_at<=now()) ORDER BY created_at LIMIT 20`).catch(()=>[]);for(const row of rows){try{await this.sendCampaign({organizationId:row.organization_id,projectId:row.project_id,environmentId:row.environment_id,userId:row.created_by||'system',role:'service'},row.id);}catch{/* persisted by sendCampaign */}}}
  private async cleanupRetention():Promise<void>{const analyticsDays=clampRetentionDays(process.env.ANALYTICS_RETENTION_DAYS,90);const qualityDays=clampRetentionDays(process.env.APP_QUALITY_RETENTION_DAYS,90);const aiDays=clampRetentionDays(process.env.AI_USAGE_RETENTION_DAYS,90);await Promise.all([postgres.execute(`DELETE FROM analytics_events WHERE occurred_at < now() - ($1::int * interval '1 day')`,[analyticsDays]),postgres.execute(`DELETE FROM app_quality_events WHERE occurred_at < now() - ($1::int * interval '1 day')`,[qualityDays]),postgres.execute(`DELETE FROM ai_usage WHERE created_at < now() - ($1::int * interval '1 day')`,[aiDays])]).catch(()=>undefined);}
}

export const advancedPlatformEngine = new AdvancedPlatformEngine();
