/* eslint-disable no-console */
const fs=require('node:fs');const path=require('node:path');const {isSemVerAtLeast}=require('./semver.cjs');const root=path.resolve(__dirname,'..');const failures=[];
const read=(file)=>fs.readFileSync(path.join(root,file),'utf8');const exists=(file)=>fs.existsSync(path.join(root,file));
const required=['server/db/migrations/018_auth_phase3.sql','server/auth/webauthn.ts','server/auth/smsService.ts','server/routes/realAuth.ts','server/auth/oauth.ts','src/brisabase/pages/AuthPage.tsx','PHASE3_COMPLETION.md'];
for(const file of required)if(!exists(file))failures.push(`missing Phase 3 file: ${file}`);
const migrationFiles=fs.readdirSync(path.join(root,'server/db/migrations')).filter(x=>/^\d+_.*\.sql$/.test(x));const prefixes=new Map();for(const file of migrationFiles){const n=file.split('_')[0];if(prefixes.has(n))failures.push(`duplicate migration prefix ${n}: ${prefixes.get(n)} / ${file}`);else prefixes.set(n,file);}
const pkg=JSON.parse(read('package.json'));const sdk=JSON.parse(read('developer/sdk/package.json'));if(!isSemVerAtLeast(pkg.version,'0.5.0'))failures.push('platform version must be valid SemVer and Phase 3 (0.5.0) or newer');if(sdk.version!==pkg.version)failures.push('SDK version must match platform');if(!read('developer/cli/brisabase.mjs').includes(`const VERSION = '${pkg.version}'`))failures.push('CLI version must match platform');
const mig=read('server/db/migrations/018_auth_phase3.sql');for(const token of ['auth_identities','auth_one_time_codes','auth_passkeys','auth_custom_roles','custom_claims','magic_link_enabled','phone_otp_enabled','allowed_redirect_origins'])if(!mig.includes(token))failures.push(`auth migration missing ${token}`);
const route=read('server/routes/realAuth.ts');for(const endpoint of ['/api/auth/magic-link/request','/api/auth/email-otp/request','/api/auth/phone-otp/request','/api/auth/anonymous','/api/auth/anonymous/convert','/api/auth/mfa/enroll','/api/auth/mfa/challenge','/api/auth/passkeys/register/options','/api/auth/passkeys/authenticate/verify','/api/auth/oauth/:provider/link','/auth/users/:userId/authorization','/auth/roles'])if(!route.includes(endpoint))failures.push(`auth route missing ${endpoint}`);
for(const token of ['ACCOUNT_LINK_REQUIRED','auth.refresh_reuse_detected','revokeUserSessionsExcept','deletePendingMfaFactors','passwordlessResult','validateSettingsUpdate','mfa_enrollment_required'])if(!route.includes(token))failures.push(`auth security flow missing ${token}`);
if(/issue\([^\n]*settings\.require_mfa/.test(route))failures.push('passwordless routes must not mark MFA verified from project settings alone');
const oauth=read('server/auth/oauth.ts');for(const p of ['google','github','microsoft','discord','apple'])if(!oauth.includes(`case'${p}'`))failures.push(`OAuth provider missing ${p}`);if(!oauth.includes('verifyAppleIdentityToken'))failures.push('Apple id_token verification is missing');
const webauthn=read('server/auth/webauthn.ts');for(const token of ['WebAuthn challenge is invalid','WebAuthn origin is not allowed','WebAuthn RP ID does not match','User verification is required','Passkey signature is invalid','signature counter did not advance'])if(!webauthn.includes(token))failures.push(`WebAuthn verification missing: ${token}`);
const repo=read('server/auth/realAuthRepository.ts');for(const token of ['findRefreshTokenAny','deleteOtherMfaFactors','findIdentityById','convertAnonymousUser','auth_custom_roles'])if(!repo.includes(token))failures.push(`Auth repository missing ${token}`);
const jwt=read('server/auth/jwt.ts'),crypto=read('server/auth/cryptoUtils.ts');if(!jwt.includes('JWT_SECRET_PREVIOUS'))failures.push('JWT rotation keyring missing');if(!crypto.includes('AUTH_ENCRYPTION_KEY_PREVIOUS'))failures.push('auth encryption key rotation missing');
const gateway=read('server/apiEngine/apiGateway.ts');if(!gateway.includes('securityRole')||!gateway.includes('payload.role'))failures.push('custom JWT role must reach the RLS security context');
const middleware=read('server/middleware/auth.ts');if(!middleware.includes("mfa\\/(challenge|enroll|verify)")||!middleware.includes('realAuthRepository.touchSession'))failures.push('end-user auth middleware protections are incomplete');
const ui=read('src/brisabase/pages/AuthPage.tsx');for(const token of ['Roles & Claims','Sessões','Passkeys / WebAuthn','OTP por telefone','allowed_redirect_origins','revokeSession'])if(!ui.includes(token))failures.push(`Auth management UI missing ${token}`);
for(const file of ['.env.example','.env.production.example','docker-compose.production.yml']){const text=read(file);for(const token of ['AUTH_WEBAUTHN_RP_ID','TWILIO_ACCOUNT_SID','JWT_SECRET_PREVIOUS','AUTH_ENCRYPTION_KEY_PREVIOUS'])if(!text.includes(token))failures.push(`${file} missing ${token}`);}
const validator=read('scripts/validate-production-env.cjs');for(const token of ['JWT_SECRET_PREVIOUS','AUTH_ENCRYPTION_KEY_PREVIOUS','Twilio SMS','AUTH_WEBAUTHN_ORIGINS'])if(!validator.includes(token))failures.push(`production validator missing ${token}`);
if(failures.length){console.error('[BRISABASE PHASE 3 VERIFY] FAILED');failures.forEach(x=>console.error(`- ${x}`));process.exit(1);}console.log('[BRISABASE PHASE 3 VERIFY] PASS');
