import crypto from 'node:crypto';
import { postgres } from '../db/postgres';

type IacContext={organizationId:string;projectId:string;environmentId:string;userId:string;role:string};
const id=(p:string)=>`${p}_${crypto.randomUUID().replace(/-/g,'').slice(0,24)}`;
function manage(ctx:IacContext){if(!['owner','admin','developer'].includes(ctx.role))throw new Error('IaC export requires write access.');}
function canonical(value:any):any{if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object'){return Object.fromEntries(Object.keys(value).filter(key=>key!=='generatedAt').sort().map(key=>[key,canonical(value[key])]));}return value;}
const stable=(value:any)=>JSON.stringify(canonical(value),null,2);
const checksum=(value:any)=>crypto.createHash('sha256').update(stable(value)).digest('hex');
function hclString(value:any){return JSON.stringify(String(value));}

export class IacEngine{
  public async manifest(ctx:IacContext):Promise<any>{manage(ctx);const [project,environment,buckets,functions,webhooks,sites,flags,providers,settings]=await Promise.all([
    postgres.query<any>('SELECT id,name,slug,description,region,status FROM projects WHERE id=$1 AND organization_id=$2',[ctx.projectId,ctx.organizationId]),
    postgres.query<any>('SELECT id,name,slug,type,status FROM project_environments WHERE id=$1 AND project_id=$2',[ctx.environmentId,ctx.projectId]),
    postgres.query<any>('SELECT name,is_public,file_size_limit,allowed_mime_types,versioning_enabled,cors_config,lifecycle_rules FROM storage_buckets WHERE project_id=$1 AND environment_id=$2 ORDER BY name',[ctx.projectId,ctx.environmentId]),
    postgres.query<any>('SELECT slug,name,description,runtime,entrypoint,access,execution_mode,limits,status FROM functions WHERE project_id=$1 AND environment_id=$2 ORDER BY slug',[ctx.projectId,ctx.environmentId]),
    postgres.query<any>('SELECT name,target_url,events,max_attempts,timeout_ms,enabled FROM webhooks WHERE project_id=$1 AND environment_id=$2 ORDER BY name',[ctx.projectId,ctx.environmentId]),
    postgres.query<any>('SELECT id,name,slug,public_env,redirects,rewrites FROM hosting_sites WHERE project_id=$1 AND environment_id=$2 ORDER BY slug',[ctx.projectId,ctx.environmentId]).catch(()=>[]),
    postgres.query<any>('SELECT key,value,enabled,rollout_basis_points,rules FROM feature_flags WHERE project_id=$1 AND environment_id=$2 ORDER BY key',[ctx.projectId,ctx.environmentId]),
    postgres.query<any>('SELECT provider,enabled,client_id,redirect_url FROM auth_provider_configs WHERE project_id=$1 AND environment_id=$2 ORDER BY provider',[ctx.projectId,ctx.environmentId]).catch(()=>[]),
    postgres.query<any>('SELECT key,value FROM project_settings WHERE project_id=$1 AND (environment_id=$2 OR environment_id IS NULL) ORDER BY key',[ctx.projectId,ctx.environmentId]),
  ]);if(!project[0]||!environment[0])throw new Error('IaC project/environment scope is invalid.');return{apiVersion:'brisabase.io/v1',kind:'EnvironmentManifest',organizationId:ctx.organizationId,project:project[0],environment:environment[0],resources:{storageBuckets:buckets,functions,webhooks,hostingSites:sites,featureFlags:flags,authProviders:providers.map((x:any)=>({...x,client_id:x.client_id?'configured':null})),settings},generatedAt:new Date().toISOString()};}
  public terraform(manifest:any):string{const resources=manifest.resources||{};const lines=[`terraform {`,`  required_version = ">= 1.6.0"`,`}`,``,`# BrisaBase 1.0 Terraform bridge. The native state remains in BrisaBase;`,`# this module calls the BrisaBase CLI with a checksum-pinned manifest.`,`variable "brisabase_url" { type = string }`,`variable "brisabase_token" { type = string; sensitive = true }`,``,`locals {`,`  manifest_sha256 = ${hclString(checksum(manifest))}`,`}`,``,`resource "terraform_data" "brisabase_environment" {`,`  input = {`,`    manifest_sha256 = local.manifest_sha256`,`    project_id = ${hclString(manifest.project?.id)}`,`    environment_id = ${hclString(manifest.environment?.id)}`,`  }`,``,`  provisioner "local-exec" {`,`    command = "brisabase iac check brisabase.manifest.json --expected-sha ${'${local.manifest_sha256}'}"`,`    environment = {`,`      BRISABASE_URL = var.brisabase_url`,`      BRISABASE_TOKEN = var.brisabase_token`,`    }`,`  }`,`}`,``,`# Exported resources: ${Object.entries(resources).map(([k,v]:any)=>`${k}=${Array.isArray(v)?v.length:0}`).join(', ')}`,``];return lines.join('\n');}
  public async export(ctx:IacContext,provider:'json'|'terraform'='json'){const manifest=await this.manifest(ctx);const hash=checksum(manifest);await postgres.execute('INSERT INTO iac_exports(id,organization_id,project_id,environment_id,provider,checksum,manifest,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id('iac'),ctx.organizationId,ctx.projectId,ctx.environmentId,provider,hash,JSON.stringify(manifest),ctx.userId]);return provider==='terraform'?{provider,checksum:hash,manifest,terraform:this.terraform(manifest)}:{provider,checksum:hash,manifest};}
  public async history(ctx:IacContext){return postgres.query<any>('SELECT id,provider,checksum,created_at AS "createdAt" FROM iac_exports WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY created_at DESC LIMIT 100',[ctx.organizationId,ctx.projectId,ctx.environmentId]);}
  public async diff(ctx:IacContext,expected:any){const actual=await this.manifest(ctx);const expectedHash=checksum(expected);const actualHash=checksum(actual);const differences:string[]=[];const walk=(a:any,b:any,path='')=>{const keys=new Set([...Object.keys(a||{}),...Object.keys(b||{})]);for(const key of [...keys].sort()){if(['generatedAt'].includes(key))continue;const av=a?.[key],bv=b?.[key],p=path?`${path}.${key}`:key;if(Array.isArray(av)||Array.isArray(bv)){if(JSON.stringify(av)!==JSON.stringify(bv))differences.push(p);continue;}if(av&&typeof av==='object'||bv&&typeof bv==='object')walk(av||{},bv||{},p);else if(av!==bv)differences.push(p);}};walk(expected,actual);return{drift:differences.length>0,expectedHash,actualHash,differences:differences.slice(0,500)};}
}
export const iacEngine=new IacEngine();
