type JsonInit = Omit<RequestInit,'body'> & {body?:unknown};
async function request<T>(url:string,init:JsonInit={}):Promise<T>{const headers=new Headers(init.headers||{});let body:BodyInit|undefined;if(init.body!==undefined){headers.set('Content-Type','application/json');body=JSON.stringify(init.body);}const response=await fetch(url,{...init,headers,body});const payload=response.status===204?null:await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error?.message||`BrisaBase request failed (${response.status}).`);return payload as T;}

export const advancedPlatformService={
  segments:{list:()=>request<any[]>('/api/advanced/segments'),save:(input:any)=>request('/api/advanced/segments',{method:'POST',body:input}),remove:(id:string)=>request(`/api/advanced/segments/${encodeURIComponent(id)}`,{method:'DELETE'})},
  config:{list:()=>request<any[]>('/api/advanced/config'),save:(key:string,input:any)=>request(`/api/advanced/config/${encodeURIComponent(key)}`,{method:'PUT',body:input}),remove:(key:string)=>request(`/api/advanced/config/${encodeURIComponent(key)}`,{method:'DELETE'})},
  flags:{list:()=>request<any[]>('/api/advanced/flags'),save:(key:string,input:any)=>request(`/api/advanced/flags/${encodeURIComponent(key)}`,{method:'PUT',body:input}),remove:(key:string)=>request(`/api/advanced/flags/${encodeURIComponent(key)}`,{method:'DELETE'})},
  experiments:{list:()=>request<any[]>('/api/advanced/experiments'),create:(input:any)=>request('/api/advanced/experiments',{method:'POST',body:input}),status:(id:string,status:string,winnerVariant?:string)=>request(`/api/advanced/experiments/${encodeURIComponent(id)}/status`,{method:'POST',body:{status,winnerVariant}}),metrics:(id:string)=>request<any>(`/api/advanced/experiments/${encodeURIComponent(id)}/metrics`)},
  analytics:{overview:(days=30)=>request<any>(`/api/advanced/analytics/overview?days=${days}`),funnel:(events:string[],days=30)=>request<any>('/api/advanced/analytics/funnel',{method:'POST',body:{events,days}}),retention:(firstEvent:string,returnEvent:string,days=30)=>request<any>('/api/advanced/analytics/retention',{method:'POST',body:{firstEvent,returnEvent,days}})},
  quality:{overview:(days=30)=>request<any>(`/api/advanced/quality/overview?days=${days}`),events:(limit=200)=>request<any[]>(`/api/advanced/quality/events?limit=${limit}`),distribution:()=>request<any[]>('/api/advanced/distribution'),createRelease:(input:any)=>request('/api/advanced/distribution',{method:'POST',body:input})},
  search:{indexes:()=>request<any[]>('/api/advanced/search/indexes'),saveIndex:(input:any)=>request('/api/advanced/search/indexes',{method:'POST',body:input}),upsert:(key:string,documents:any[])=>request(`/api/advanced/search/indexes/${encodeURIComponent(key)}/documents`,{method:'PUT',body:{documents}}),query:(key:string,input:any)=>request<any>(`/api/advanced/search/indexes/${encodeURIComponent(key)}/query`,{method:'POST',body:input})},
  ai:{providers:()=>request<any[]>('/api/advanced/ai/providers'),saveProvider:(key:string,input:any)=>request(`/api/advanced/ai/providers/${encodeURIComponent(key)}`,{method:'PUT',body:input}),removeProvider:(id:string)=>request(`/api/advanced/ai/providers/${encodeURIComponent(id)}`,{method:'DELETE'}),usage:(days=30)=>request<any>(`/api/advanced/ai/usage?days=${days}`),generate:(input:any)=>request<any>('/api/advanced/ai/generate',{method:'POST',body:input}),embed:(input:any)=>request<any>('/api/advanced/ai/embeddings',{method:'POST',body:input}),rag:(input:any)=>request<any>('/api/advanced/ai/rag',{method:'POST',body:input})},
  messaging:{templates:()=>request<any[]>('/api/advanced/messaging/templates'),saveTemplate:(input:any)=>request('/api/advanced/messaging/templates',{method:'POST',body:input}),campaigns:()=>request<any[]>('/api/advanced/messaging/campaigns'),createCampaign:(input:any)=>request('/api/advanced/messaging/campaigns',{method:'POST',body:input}),send:(id:string)=>request(`/api/advanced/messaging/campaigns/${encodeURIComponent(id)}/send`,{method:'POST'}),cancel:(id:string)=>request(`/api/advanced/messaging/campaigns/${encodeURIComponent(id)}`,{method:'DELETE'})},
};
