class EnterpriseService {
  private async request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,init);const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error?.message||`Enterprise request failed (${response.status}).`);return payload as T;}
  domains={list:()=>this.request<any[]>('/api/enterprise/domains'),create:(domain:string)=>this.request<any>('/api/enterprise/domains',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain})}),verify:(id:string)=>this.request<any>(`/api/enterprise/domains/${encodeURIComponent(id)}/verify`,{method:'POST'}),remove:(id:string)=>this.request<void>(`/api/enterprise/domains/${encodeURIComponent(id)}`,{method:'DELETE'})};
  sso={list:()=>this.request<any[]>('/api/enterprise/sso'),save:(input:any)=>this.request<any>(input.id?`/api/enterprise/sso/${encodeURIComponent(input.id)}`:'/api/enterprise/sso',{method:input.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),remove:(id:string)=>this.request<void>(`/api/enterprise/sso/${encodeURIComponent(id)}`,{method:'DELETE'})};
  scim={list:()=>this.request<any[]>('/api/enterprise/scim/tokens'),create:(name:string)=>this.request<any>('/api/enterprise/scim/tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}),revoke:(id:string)=>this.request<void>(`/api/enterprise/scim/tokens/${encodeURIComponent(id)}`,{method:'DELETE'})};
  ips={list:()=>this.request<any[]>('/api/enterprise/ip-allowlist'),add:(cidr:string,label:string)=>this.request<any>('/api/enterprise/ip-allowlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cidr,label})}),remove:(id:string)=>this.request<void>(`/api/enterprise/ip-allowlist/${encodeURIComponent(id)}`,{method:'DELETE'})};
  policies={list:()=>this.request<Record<string,any>>('/api/enterprise/policies'),set:(key:string,value:any)=>this.request<any>(`/api/enterprise/policies/${encodeURIComponent(key)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})})};
  roles={list:()=>this.request<any[]>('/api/enterprise/roles'),save:(input:any)=>this.request<any>('/api/enterprise/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),remove:(id:string)=>this.request<void>(`/api/enterprise/roles/${encodeURIComponent(id)}`,{method:'DELETE'})};
  siem={list:()=>this.request<any[]>('/api/enterprise/siem'),save:(input:any)=>this.request<any>('/api/enterprise/siem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),remove:(id:string)=>this.request<void>(`/api/enterprise/siem/${encodeURIComponent(id)}`,{method:'DELETE'}),deliver:(id:string)=>this.request<any>(`/api/enterprise/siem/${encodeURIComponent(id)}/deliver`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})};
  compliance=()=>this.request<any>('/api/enterprise/compliance');
  iac={export:(provider:'json'|'terraform')=>this.request<any>(`/api/iac/export?provider=${provider}`),history:()=>this.request<any[]>('/api/iac/history'),diff:(manifest:any)=>this.request<any>('/api/iac/diff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({manifest})})};
}
export const enterpriseService=new EnterpriseService();
