const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'../..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const assert=(v,m)=>{if(!v)throw new Error(m)};
const migration=read('server/db/migrations/019_storage_realtime_webhooks_phase4.sql');
assert(migration.includes('cors_config')&&migration.includes('lifecycle_rules'),'storage bucket policy fields missing');
assert(migration.includes('storage_multipart_uploads'),'multipart persistence missing');
assert(migration.includes('CREATE TABLE IF NOT EXISTS webhooks'),'webhooks table missing');
assert(migration.includes('CREATE TABLE IF NOT EXISTS webhook_deliveries'),'webhook delivery table missing');
assert(migration.includes('idx_webhook_deliveries_event_once'),'webhook event idempotency index missing');
const wh=read('server/webhooks/webhookEngine.ts');
for(const token of ['createHmac','redirect:\'error\'','privateAddress','dead_letter','max_attempts','x-brisabase-signature','RESERVED_WEBHOOK_HEADERS','FOR UPDATE OF d SKIP LOCKED']) assert(wh.includes(token),`webhook safety contract missing ${token}`);
assert(/status='processing'.*interval '2 minutes'/s.test(wh),'stuck webhook delivery recovery missing');
assert(wh.includes('ON CONFLICT(webhook_id,event_id) DO NOTHING'),'webhook event enqueue must be idempotent');
const auth=read('server/middleware/auth.ts');
for (const token of ['database','realtime','webhooks','backups']) assert(auth.includes(token),`project scope boundary missing ${token}`);
const storage=read('server/storage/realStorageEngine.ts');
for(const token of ['normalizeCorsRules','normalizeLifecycleRules','uploadMultipartPart','completeMultipart','abortMultipart','transformImage','copyObject','moveObject']) assert(storage.includes(token),`storage phase4 contract missing ${token}`);
assert(storage.includes('cors_config,lifecycle_rules'),'backup restore does not retain bucket CORS/lifecycle');
const realtime=read('server/routes/realtime.ts');
assert(realtime.includes('getActiveConnectionsCount(projId, envId)'),'realtime connection metrics are not tenant scoped');
assert(realtime.includes('getActiveChannelsCount(projId, envId)'),'realtime channel metrics are not tenant scoped');
assert(realtime.includes('getCount(projId, envId)'),'realtime subscription metrics are not tenant scoped');
const sdk=read('developer/sdk/client.ts');
assert(sdk.includes('scheduleReconnect')&&sdk.includes("type: 'heartbeat'"),'SDK reconnect/heartbeat contract missing');
const cors=read('server/middleware/cors.ts');
assert(cors.includes('bucketCorsRoute'),'bucket-level public storage CORS is not delegated');
console.log('Storage + Realtime + Webhooks Phase 4 contract: PASS');
